// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <ArduinoEigen/Eigen/Core>

namespace gnc {

/**
 * This function was autogenerated. Do not modify by hand.
 *
 * Args:
 *     P: Matrix15_15
 *     H: Matrix3_15
 *     R: Scalar
 *
 * Outputs:
 *     innov_var: Matrix31
 */
template <typename Scalar>
void ComputeAttitudeInnovVar(const Eigen::Matrix<Scalar, 15, 15>& P,
                             const Eigen::Matrix<Scalar, 3, 15>& H, const Scalar R,
                             Eigen::Matrix<Scalar, 3, 1>* const innov_var = nullptr) {
  // Total ops: 63

  // Input arrays

  // Intermediate terms (0)

  // Output terms (1)
  if (innov_var != nullptr) {
    Eigen::Matrix<Scalar, 3, 1>& _innov_var = (*innov_var);

    _innov_var(0, 0) = H(0, 6) * (H(0, 6) * P(6, 6) + H(0, 7) * P(7, 6) + H(0, 8) * P(8, 6)) +
                       H(0, 7) * (H(0, 6) * P(6, 7) + H(0, 7) * P(7, 7) + H(0, 8) * P(8, 7)) +
                       H(0, 8) * (H(0, 6) * P(6, 8) + H(0, 7) * P(7, 8) + H(0, 8) * P(8, 8)) + R;
    _innov_var(1, 0) = H(1, 6) * (H(1, 6) * P(6, 6) + H(1, 7) * P(7, 6) + H(1, 8) * P(8, 6)) +
                       H(1, 7) * (H(1, 6) * P(6, 7) + H(1, 7) * P(7, 7) + H(1, 8) * P(8, 7)) +
                       H(1, 8) * (H(1, 6) * P(6, 8) + H(1, 7) * P(7, 8) + H(1, 8) * P(8, 8)) + R;
    _innov_var(2, 0) = H(2, 6) * (H(2, 6) * P(6, 6) + H(2, 7) * P(7, 6) + H(2, 8) * P(8, 6)) +
                       H(2, 7) * (H(2, 6) * P(6, 7) + H(2, 7) * P(7, 7) + H(2, 8) * P(8, 7)) +
                       H(2, 8) * (H(2, 6) * P(6, 8) + H(2, 7) * P(7, 8) + H(2, 8) * P(8, 8)) + R;
  }
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace gnc
