// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <ArduinoEigen/Eigen/Core>

namespace gnc {

/**
 * This function was autogenerated. Do not modify by hand.
 *
 * Args:
 *     innov: Matrix31
 *     meas_cov: Matrix33
 *     P: Matrix15_15
 *     H_theta: Matrix33
 *
 * Outputs:
 *     error_state: Matrix15_1
 *     P_updated: Matrix15_15
 *     innov_cov: Matrix33
 */
template <typename Scalar>
void FuseAttitude(const Eigen::Matrix<Scalar, 3, 1>& innov,
                  const Eigen::Matrix<Scalar, 3, 3>& meas_cov,
                  const Eigen::Matrix<Scalar, 15, 15>& P,
                  const Eigen::Matrix<Scalar, 3, 3>& H_theta,
                  Eigen::Matrix<Scalar, 15, 1>* const error_state = nullptr,
                  Eigen::Matrix<Scalar, 15, 15>* const P_updated = nullptr,
                  Eigen::Matrix<Scalar, 3, 3>* const innov_cov = nullptr) {
  // Total ops: 5032

  // Input arrays

  // Intermediate terms (253)
  const Scalar _tmp0 = H_theta(1, 0) * P(0, 6) + H_theta(1, 1) * P(0, 7) + H_theta(1, 2) * P(0, 8);
  const Scalar _tmp1 = H_theta(1, 0) * P(7, 6) + H_theta(1, 1) * P(7, 7) + H_theta(1, 2) * P(7, 8);
  const Scalar _tmp2 = H_theta(1, 0) * P(8, 6) + H_theta(1, 1) * P(8, 7) + H_theta(1, 2) * P(8, 8);
  const Scalar _tmp3 = H_theta(1, 0) * P(6, 6) + H_theta(1, 1) * P(6, 7) + H_theta(1, 2) * P(6, 8);
  const Scalar _tmp4 =
      H_theta(0, 0) * _tmp3 + H_theta(0, 1) * _tmp1 + H_theta(0, 2) * _tmp2 + meas_cov(0, 1);
  const Scalar _tmp5 = H_theta(0, 0) * P(7, 6) + H_theta(0, 1) * P(7, 7) + H_theta(0, 2) * P(7, 8);
  const Scalar _tmp6 = H_theta(0, 0) * P(8, 6) + H_theta(0, 1) * P(8, 7) + H_theta(0, 2) * P(8, 8);
  const Scalar _tmp7 = H_theta(0, 0) * P(6, 6) + H_theta(0, 1) * P(6, 7) + H_theta(0, 2) * P(6, 8);
  const Scalar _tmp8 =
      H_theta(0, 0) * _tmp7 + H_theta(0, 1) * _tmp5 + H_theta(0, 2) * _tmp6 + meas_cov(0, 0);
  const Scalar _tmp9 = Scalar(1.0) / (_tmp8);
  const Scalar _tmp10 =
      H_theta(1, 0) * _tmp7 + H_theta(1, 1) * _tmp5 + H_theta(1, 2) * _tmp6 + meas_cov(1, 0);
  const Scalar _tmp11 = _tmp10 * _tmp9;
  const Scalar _tmp12 =
      H_theta(1, 0) * _tmp3 + H_theta(1, 1) * _tmp1 + H_theta(1, 2) * _tmp2 + meas_cov(1, 1);
  const Scalar _tmp13 = Scalar(1.0) / (-_tmp11 * _tmp4 + _tmp12);
  const Scalar _tmp14 = H_theta(2, 0) * P(7, 6) + H_theta(2, 1) * P(7, 7) + H_theta(2, 2) * P(7, 8);
  const Scalar _tmp15 = H_theta(2, 0) * P(6, 6) + H_theta(2, 1) * P(6, 7) + H_theta(2, 2) * P(6, 8);
  const Scalar _tmp16 = H_theta(2, 0) * P(8, 6) + H_theta(2, 1) * P(8, 7) + H_theta(2, 2) * P(8, 8);
  const Scalar _tmp17 =
      H_theta(0, 0) * _tmp15 + H_theta(0, 1) * _tmp14 + H_theta(0, 2) * _tmp16 + meas_cov(0, 2);
  const Scalar _tmp18 =
      H_theta(2, 0) * _tmp7 + H_theta(2, 1) * _tmp5 + H_theta(2, 2) * _tmp6 + meas_cov(2, 0);
  const Scalar _tmp19 = _tmp18 * _tmp9;
  const Scalar _tmp20 =
      H_theta(1, 0) * _tmp15 + H_theta(1, 1) * _tmp14 + H_theta(1, 2) * _tmp16 + meas_cov(1, 2);
  const Scalar _tmp21 = -_tmp11 * _tmp17 + _tmp20;
  const Scalar _tmp22 =
      H_theta(2, 0) * _tmp3 + H_theta(2, 1) * _tmp1 + H_theta(2, 2) * _tmp2 + meas_cov(2, 1);
  const Scalar _tmp23 = _tmp13 * (-_tmp19 * _tmp4 + _tmp22);
  const Scalar _tmp24 =
      H_theta(2, 0) * _tmp15 + H_theta(2, 1) * _tmp14 + H_theta(2, 2) * _tmp16 + meas_cov(2, 2);
  const Scalar _tmp25 = Scalar(1.0) / (-_tmp17 * _tmp19 - _tmp21 * _tmp23 + _tmp24);
  const Scalar _tmp26 = _tmp21 * _tmp25;
  const Scalar _tmp27 = _tmp13 * _tmp26;
  const Scalar _tmp28 =
      _tmp25 * (H_theta(2, 0) * P(0, 6) + H_theta(2, 1) * P(0, 7) + H_theta(2, 2) * P(0, 8));
  const Scalar _tmp29 = H_theta(0, 0) * P(0, 6) + H_theta(0, 1) * P(0, 7) + H_theta(0, 2) * P(0, 8);
  const Scalar _tmp30 = _tmp17 * _tmp25;
  const Scalar _tmp31 = _tmp9 * (_tmp27 * _tmp4 - _tmp30);
  const Scalar _tmp32 = -_tmp0 * _tmp27 + _tmp28 + _tmp29 * _tmp31;
  const Scalar _tmp33 = _tmp11 * _tmp23 - _tmp19;
  const Scalar _tmp34 = _tmp13 * (-_tmp11 - _tmp26 * _tmp33);
  const Scalar _tmp35 = _tmp9 * (-_tmp30 * _tmp33 - _tmp34 * _tmp4 + 1);
  const Scalar _tmp36 = _tmp0 * _tmp34 + _tmp28 * _tmp33 + _tmp29 * _tmp35;
  const Scalar _tmp37 = _tmp13 * (_tmp23 * _tmp26 + 1);
  const Scalar _tmp38 = _tmp9 * (_tmp23 * _tmp30 - _tmp37 * _tmp4);
  const Scalar _tmp39 = _tmp0 * _tmp37 - _tmp23 * _tmp28 + _tmp29 * _tmp38;
  const Scalar _tmp40 =
      _tmp25 * (H_theta(2, 0) * P(1, 6) + H_theta(2, 1) * P(1, 7) + H_theta(2, 2) * P(1, 8));
  const Scalar _tmp41 = H_theta(0, 0) * P(1, 6) + H_theta(0, 1) * P(1, 7) + H_theta(0, 2) * P(1, 8);
  const Scalar _tmp42 = H_theta(1, 0) * P(1, 6) + H_theta(1, 1) * P(1, 7) + H_theta(1, 2) * P(1, 8);
  const Scalar _tmp43 = _tmp33 * _tmp40 + _tmp34 * _tmp42 + _tmp35 * _tmp41;
  const Scalar _tmp44 = -_tmp27 * _tmp42 + _tmp31 * _tmp41 + _tmp40;
  const Scalar _tmp45 = -_tmp23 * _tmp40 + _tmp37 * _tmp42 + _tmp38 * _tmp41;
  const Scalar _tmp46 = H_theta(1, 0) * P(2, 6) + H_theta(1, 1) * P(2, 7) + H_theta(1, 2) * P(2, 8);
  const Scalar _tmp47 = H_theta(0, 0) * P(2, 6) + H_theta(0, 1) * P(2, 7) + H_theta(0, 2) * P(2, 8);
  const Scalar _tmp48 =
      _tmp25 * (H_theta(2, 0) * P(2, 6) + H_theta(2, 1) * P(2, 7) + H_theta(2, 2) * P(2, 8));
  const Scalar _tmp49 = -_tmp23 * _tmp48 + _tmp37 * _tmp46 + _tmp38 * _tmp47;
  const Scalar _tmp50 = _tmp33 * _tmp48 + _tmp34 * _tmp46 + _tmp35 * _tmp47;
  const Scalar _tmp51 = -_tmp27 * _tmp46 + _tmp31 * _tmp47 + _tmp48;
  const Scalar _tmp52 = H_theta(1, 0) * P(3, 6) + H_theta(1, 1) * P(3, 7) + H_theta(1, 2) * P(3, 8);
  const Scalar _tmp53 =
      _tmp25 * (H_theta(2, 0) * P(3, 6) + H_theta(2, 1) * P(3, 7) + H_theta(2, 2) * P(3, 8));
  const Scalar _tmp54 = H_theta(0, 0) * P(3, 6) + H_theta(0, 1) * P(3, 7) + H_theta(0, 2) * P(3, 8);
  const Scalar _tmp55 = -_tmp27 * _tmp52 + _tmp31 * _tmp54 + _tmp53;
  const Scalar _tmp56 = -_tmp23 * _tmp53 + _tmp37 * _tmp52 + _tmp38 * _tmp54;
  const Scalar _tmp57 = _tmp33 * _tmp53 + _tmp34 * _tmp52 + _tmp35 * _tmp54;
  const Scalar _tmp58 = H_theta(1, 0) * P(4, 6) + H_theta(1, 1) * P(4, 7) + H_theta(1, 2) * P(4, 8);
  const Scalar _tmp59 = H_theta(0, 0) * P(4, 6) + H_theta(0, 1) * P(4, 7) + H_theta(0, 2) * P(4, 8);
  const Scalar _tmp60 =
      _tmp25 * (H_theta(2, 0) * P(4, 6) + H_theta(2, 1) * P(4, 7) + H_theta(2, 2) * P(4, 8));
  const Scalar _tmp61 = -_tmp27 * _tmp58 + _tmp31 * _tmp59 + _tmp60;
  const Scalar _tmp62 = _tmp33 * _tmp60 + _tmp34 * _tmp58 + _tmp35 * _tmp59;
  const Scalar _tmp63 = -_tmp23 * _tmp60 + _tmp37 * _tmp58 + _tmp38 * _tmp59;
  const Scalar _tmp64 =
      _tmp25 * (H_theta(2, 0) * P(5, 6) + H_theta(2, 1) * P(5, 7) + H_theta(2, 2) * P(5, 8));
  const Scalar _tmp65 = H_theta(1, 0) * P(5, 6) + H_theta(1, 1) * P(5, 7) + H_theta(1, 2) * P(5, 8);
  const Scalar _tmp66 = H_theta(0, 0) * P(5, 6) + H_theta(0, 1) * P(5, 7) + H_theta(0, 2) * P(5, 8);
  const Scalar _tmp67 = -_tmp27 * _tmp65 + _tmp31 * _tmp66 + _tmp64;
  const Scalar _tmp68 = -_tmp23 * _tmp64 + _tmp37 * _tmp65 + _tmp38 * _tmp66;
  const Scalar _tmp69 = _tmp33 * _tmp64 + _tmp34 * _tmp65 + _tmp35 * _tmp66;
  const Scalar _tmp70 = _tmp15 * _tmp25;
  const Scalar _tmp71 = -_tmp27 * _tmp3 + _tmp31 * _tmp7 + _tmp70;
  const Scalar _tmp72 = _tmp3 * _tmp34 + _tmp33 * _tmp70 + _tmp35 * _tmp7;
  const Scalar _tmp73 = -_tmp23 * _tmp70 + _tmp3 * _tmp37 + _tmp38 * _tmp7;
  const Scalar _tmp74 = _tmp14 * _tmp25;
  const Scalar _tmp75 = _tmp1 * _tmp34 + _tmp33 * _tmp74 + _tmp35 * _tmp5;
  const Scalar _tmp76 = -_tmp1 * _tmp27 + _tmp31 * _tmp5 + _tmp74;
  const Scalar _tmp77 = _tmp1 * _tmp37 - _tmp23 * _tmp74 + _tmp38 * _tmp5;
  const Scalar _tmp78 = _tmp16 * _tmp25;
  const Scalar _tmp79 = _tmp2 * _tmp37 - _tmp23 * _tmp78 + _tmp38 * _tmp6;
  const Scalar _tmp80 = _tmp2 * _tmp34 + _tmp33 * _tmp78 + _tmp35 * _tmp6;
  const Scalar _tmp81 = -_tmp2 * _tmp27 + _tmp31 * _tmp6 + _tmp78;
  const Scalar _tmp82 = H_theta(1, 0) * P(9, 6) + H_theta(1, 1) * P(9, 7) + H_theta(1, 2) * P(9, 8);
  const Scalar _tmp83 = H_theta(0, 0) * P(9, 6) + H_theta(0, 1) * P(9, 7) + H_theta(0, 2) * P(9, 8);
  const Scalar _tmp84 =
      _tmp25 * (H_theta(2, 0) * P(9, 6) + H_theta(2, 1) * P(9, 7) + H_theta(2, 2) * P(9, 8));
  const Scalar _tmp85 = -_tmp27 * _tmp82 + _tmp31 * _tmp83 + _tmp84;
  const Scalar _tmp86 = -_tmp23 * _tmp84 + _tmp37 * _tmp82 + _tmp38 * _tmp83;
  const Scalar _tmp87 = _tmp33 * _tmp84 + _tmp34 * _tmp82 + _tmp35 * _tmp83;
  const Scalar _tmp88 =
      H_theta(0, 0) * P(10, 6) + H_theta(0, 1) * P(10, 7) + H_theta(0, 2) * P(10, 8);
  const Scalar _tmp89 =
      H_theta(1, 0) * P(10, 6) + H_theta(1, 1) * P(10, 7) + H_theta(1, 2) * P(10, 8);
  const Scalar _tmp90 =
      _tmp25 * (H_theta(2, 0) * P(10, 6) + H_theta(2, 1) * P(10, 7) + H_theta(2, 2) * P(10, 8));
  const Scalar _tmp91 = -_tmp27 * _tmp89 + _tmp31 * _tmp88 + _tmp90;
  const Scalar _tmp92 = -_tmp23 * _tmp90 + _tmp37 * _tmp89 + _tmp38 * _tmp88;
  const Scalar _tmp93 = _tmp33 * _tmp90 + _tmp34 * _tmp89 + _tmp35 * _tmp88;
  const Scalar _tmp94 =
      H_theta(1, 0) * P(11, 6) + H_theta(1, 1) * P(11, 7) + H_theta(1, 2) * P(11, 8);
  const Scalar _tmp95 =
      H_theta(0, 0) * P(11, 6) + H_theta(0, 1) * P(11, 7) + H_theta(0, 2) * P(11, 8);
  const Scalar _tmp96 =
      _tmp25 * (H_theta(2, 0) * P(11, 6) + H_theta(2, 1) * P(11, 7) + H_theta(2, 2) * P(11, 8));
  const Scalar _tmp97 = _tmp33 * _tmp96 + _tmp34 * _tmp94 + _tmp35 * _tmp95;
  const Scalar _tmp98 = -_tmp27 * _tmp94 + _tmp31 * _tmp95 + _tmp96;
  const Scalar _tmp99 = -_tmp23 * _tmp96 + _tmp37 * _tmp94 + _tmp38 * _tmp95;
  const Scalar _tmp100 =
      H_theta(1, 0) * P(12, 6) + H_theta(1, 1) * P(12, 7) + H_theta(1, 2) * P(12, 8);
  const Scalar _tmp101 =
      _tmp25 * (H_theta(2, 0) * P(12, 6) + H_theta(2, 1) * P(12, 7) + H_theta(2, 2) * P(12, 8));
  const Scalar _tmp102 =
      H_theta(0, 0) * P(12, 6) + H_theta(0, 1) * P(12, 7) + H_theta(0, 2) * P(12, 8);
  const Scalar _tmp103 = _tmp100 * _tmp34 + _tmp101 * _tmp33 + _tmp102 * _tmp35;
  const Scalar _tmp104 = _tmp100 * _tmp37 - _tmp101 * _tmp23 + _tmp102 * _tmp38;
  const Scalar _tmp105 = -_tmp100 * _tmp27 + _tmp101 + _tmp102 * _tmp31;
  const Scalar _tmp106 =
      H_theta(1, 0) * P(13, 6) + H_theta(1, 1) * P(13, 7) + H_theta(1, 2) * P(13, 8);
  const Scalar _tmp107 =
      H_theta(0, 0) * P(13, 6) + H_theta(0, 1) * P(13, 7) + H_theta(0, 2) * P(13, 8);
  const Scalar _tmp108 =
      _tmp25 * (H_theta(2, 0) * P(13, 6) + H_theta(2, 1) * P(13, 7) + H_theta(2, 2) * P(13, 8));
  const Scalar _tmp109 = _tmp106 * _tmp37 + _tmp107 * _tmp38 - _tmp108 * _tmp23;
  const Scalar _tmp110 = -_tmp106 * _tmp27 + _tmp107 * _tmp31 + _tmp108;
  const Scalar _tmp111 = _tmp106 * _tmp34 + _tmp107 * _tmp35 + _tmp108 * _tmp33;
  const Scalar _tmp112 =
      _tmp25 * (H_theta(2, 0) * P(14, 6) + H_theta(2, 1) * P(14, 7) + H_theta(2, 2) * P(14, 8));
  const Scalar _tmp113 =
      H_theta(1, 0) * P(14, 6) + H_theta(1, 1) * P(14, 7) + H_theta(1, 2) * P(14, 8);
  const Scalar _tmp114 =
      H_theta(0, 0) * P(14, 6) + H_theta(0, 1) * P(14, 7) + H_theta(0, 2) * P(14, 8);
  const Scalar _tmp115 = _tmp112 - _tmp113 * _tmp27 + _tmp114 * _tmp31;
  const Scalar _tmp116 = _tmp112 * _tmp33 + _tmp113 * _tmp34 + _tmp114 * _tmp35;
  const Scalar _tmp117 = -_tmp112 * _tmp23 + _tmp113 * _tmp37 + _tmp114 * _tmp38;
  const Scalar _tmp118 =
      _tmp32 * meas_cov(2, 1) + _tmp36 * meas_cov(0, 1) + _tmp39 * meas_cov(1, 1);
  const Scalar _tmp119 =
      _tmp32 * meas_cov(2, 0) + _tmp36 * meas_cov(0, 0) + _tmp39 * meas_cov(1, 0);
  const Scalar _tmp120 =
      _tmp32 * meas_cov(2, 2) + _tmp36 * meas_cov(0, 2) + _tmp39 * meas_cov(1, 2);
  const Scalar _tmp121 = H_theta(0, 0) * _tmp36 + H_theta(1, 0) * _tmp39 + H_theta(2, 0) * _tmp32;
  const Scalar _tmp122 = H_theta(0, 1) * _tmp36 + H_theta(1, 1) * _tmp39 + H_theta(2, 1) * _tmp32;
  const Scalar _tmp123 = H_theta(0, 2) * _tmp36 + H_theta(1, 2) * _tmp39 + H_theta(2, 2) * _tmp32;
  const Scalar _tmp124 = P(0, 7) - P(6, 7) * _tmp121 - P(7, 7) * _tmp122 - P(8, 7) * _tmp123;
  const Scalar _tmp125 = P(0, 8) - P(6, 8) * _tmp121 - P(7, 8) * _tmp122 - P(8, 8) * _tmp123;
  const Scalar _tmp126 = P(0, 6) - P(6, 6) * _tmp121 - P(7, 6) * _tmp122 - P(8, 6) * _tmp123;
  const Scalar _tmp127 =
      _tmp43 * meas_cov(0, 2) + _tmp44 * meas_cov(2, 2) + _tmp45 * meas_cov(1, 2);
  const Scalar _tmp128 =
      _tmp43 * meas_cov(0, 0) + _tmp44 * meas_cov(2, 0) + _tmp45 * meas_cov(1, 0);
  const Scalar _tmp129 =
      _tmp43 * meas_cov(0, 1) + _tmp44 * meas_cov(2, 1) + _tmp45 * meas_cov(1, 1);
  const Scalar _tmp130 = H_theta(0, 2) * _tmp43 + H_theta(1, 2) * _tmp45 + H_theta(2, 2) * _tmp44;
  const Scalar _tmp131 = H_theta(0, 1) * _tmp43 + H_theta(1, 1) * _tmp45 + H_theta(2, 1) * _tmp44;
  const Scalar _tmp132 = H_theta(0, 0) * _tmp43 + H_theta(1, 0) * _tmp45 + H_theta(2, 0) * _tmp44;
  const Scalar _tmp133 = P(1, 8) - P(6, 8) * _tmp132 - P(7, 8) * _tmp131 - P(8, 8) * _tmp130;
  const Scalar _tmp134 = P(1, 7) - P(6, 7) * _tmp132 - P(7, 7) * _tmp131 - P(8, 7) * _tmp130;
  const Scalar _tmp135 = P(1, 6) - P(6, 6) * _tmp132 - P(7, 6) * _tmp131 - P(8, 6) * _tmp130;
  const Scalar _tmp136 = H_theta(0, 1) * _tmp50 + H_theta(1, 1) * _tmp49 + H_theta(2, 1) * _tmp51;
  const Scalar _tmp137 = H_theta(0, 2) * _tmp50 + H_theta(1, 2) * _tmp49 + H_theta(2, 2) * _tmp51;
  const Scalar _tmp138 = H_theta(0, 0) * _tmp50 + H_theta(1, 0) * _tmp49 + H_theta(2, 0) * _tmp51;
  const Scalar _tmp139 =
      _tmp49 * meas_cov(1, 1) + _tmp50 * meas_cov(0, 1) + _tmp51 * meas_cov(2, 1);
  const Scalar _tmp140 = P(2, 7) - P(6, 7) * _tmp138 - P(7, 7) * _tmp136 - P(8, 7) * _tmp137;
  const Scalar _tmp141 = P(2, 8) - P(6, 8) * _tmp138 - P(7, 8) * _tmp136 - P(8, 8) * _tmp137;
  const Scalar _tmp142 = P(2, 6) - P(6, 6) * _tmp138 - P(7, 6) * _tmp136 - P(8, 6) * _tmp137;
  const Scalar _tmp143 =
      _tmp49 * meas_cov(1, 0) + _tmp50 * meas_cov(0, 0) + _tmp51 * meas_cov(2, 0);
  const Scalar _tmp144 =
      _tmp49 * meas_cov(1, 2) + _tmp50 * meas_cov(0, 2) + _tmp51 * meas_cov(2, 2);
  const Scalar _tmp145 =
      _tmp55 * meas_cov(2, 1) + _tmp56 * meas_cov(1, 1) + _tmp57 * meas_cov(0, 1);
  const Scalar _tmp146 = H_theta(0, 0) * _tmp57 + H_theta(1, 0) * _tmp56 + H_theta(2, 0) * _tmp55;
  const Scalar _tmp147 = H_theta(0, 1) * _tmp57 + H_theta(1, 1) * _tmp56 + H_theta(2, 1) * _tmp55;
  const Scalar _tmp148 = H_theta(0, 2) * _tmp57 + H_theta(1, 2) * _tmp56 + H_theta(2, 2) * _tmp55;
  const Scalar _tmp149 = P(3, 6) - P(6, 6) * _tmp146 - P(7, 6) * _tmp147 - P(8, 6) * _tmp148;
  const Scalar _tmp150 = P(3, 7) - P(6, 7) * _tmp146 - P(7, 7) * _tmp147 - P(8, 7) * _tmp148;
  const Scalar _tmp151 = P(3, 8) - P(6, 8) * _tmp146 - P(7, 8) * _tmp147 - P(8, 8) * _tmp148;
  const Scalar _tmp152 =
      _tmp55 * meas_cov(2, 2) + _tmp56 * meas_cov(1, 2) + _tmp57 * meas_cov(0, 2);
  const Scalar _tmp153 =
      _tmp55 * meas_cov(2, 0) + _tmp56 * meas_cov(1, 0) + _tmp57 * meas_cov(0, 0);
  const Scalar _tmp154 = H_theta(0, 0) * _tmp62 + H_theta(1, 0) * _tmp63 + H_theta(2, 0) * _tmp61;
  const Scalar _tmp155 = H_theta(0, 1) * _tmp62 + H_theta(1, 1) * _tmp63 + H_theta(2, 1) * _tmp61;
  const Scalar _tmp156 = H_theta(0, 2) * _tmp62 + H_theta(1, 2) * _tmp63 + H_theta(2, 2) * _tmp61;
  const Scalar _tmp157 =
      _tmp61 * meas_cov(2, 2) + _tmp62 * meas_cov(0, 2) + _tmp63 * meas_cov(1, 2);
  const Scalar _tmp158 =
      _tmp61 * meas_cov(2, 1) + _tmp62 * meas_cov(0, 1) + _tmp63 * meas_cov(1, 1);
  const Scalar _tmp159 = P(4, 7) - P(6, 7) * _tmp154 - P(7, 7) * _tmp155 - P(8, 7) * _tmp156;
  const Scalar _tmp160 = P(4, 6) - P(6, 6) * _tmp154 - P(7, 6) * _tmp155 - P(8, 6) * _tmp156;
  const Scalar _tmp161 = P(4, 8) - P(6, 8) * _tmp154 - P(7, 8) * _tmp155 - P(8, 8) * _tmp156;
  const Scalar _tmp162 =
      _tmp61 * meas_cov(2, 0) + _tmp62 * meas_cov(0, 0) + _tmp63 * meas_cov(1, 0);
  const Scalar _tmp163 =
      _tmp67 * meas_cov(2, 2) + _tmp68 * meas_cov(1, 2) + _tmp69 * meas_cov(0, 2);
  const Scalar _tmp164 = H_theta(0, 1) * _tmp69 + H_theta(1, 1) * _tmp68 + H_theta(2, 1) * _tmp67;
  const Scalar _tmp165 = H_theta(0, 0) * _tmp69 + H_theta(1, 0) * _tmp68 + H_theta(2, 0) * _tmp67;
  const Scalar _tmp166 = H_theta(0, 2) * _tmp69 + H_theta(1, 2) * _tmp68 + H_theta(2, 2) * _tmp67;
  const Scalar _tmp167 =
      _tmp67 * meas_cov(2, 0) + _tmp68 * meas_cov(1, 0) + _tmp69 * meas_cov(0, 0);
  const Scalar _tmp168 = P(5, 8) - P(6, 8) * _tmp165 - P(7, 8) * _tmp164 - P(8, 8) * _tmp166;
  const Scalar _tmp169 = P(5, 7) - P(6, 7) * _tmp165 - P(7, 7) * _tmp164 - P(8, 7) * _tmp166;
  const Scalar _tmp170 = P(5, 6) - P(6, 6) * _tmp165 - P(7, 6) * _tmp164 - P(8, 6) * _tmp166;
  const Scalar _tmp171 =
      _tmp67 * meas_cov(2, 1) + _tmp68 * meas_cov(1, 1) + _tmp69 * meas_cov(0, 1);
  const Scalar _tmp172 =
      _tmp71 * meas_cov(2, 2) + _tmp72 * meas_cov(0, 2) + _tmp73 * meas_cov(1, 2);
  const Scalar _tmp173 = H_theta(0, 1) * _tmp72 + H_theta(1, 1) * _tmp73 + H_theta(2, 1) * _tmp71;
  const Scalar _tmp174 = H_theta(0, 2) * _tmp72 + H_theta(1, 2) * _tmp73 + H_theta(2, 2) * _tmp71;
  const Scalar _tmp175 =
      -H_theta(0, 0) * _tmp72 - H_theta(1, 0) * _tmp73 - H_theta(2, 0) * _tmp71 + 1;
  const Scalar _tmp176 = P(6, 6) * _tmp175 - P(7, 6) * _tmp173 - P(8, 6) * _tmp174;
  const Scalar _tmp177 = P(6, 7) * _tmp175 - P(7, 7) * _tmp173 - P(8, 7) * _tmp174;
  const Scalar _tmp178 = P(6, 8) * _tmp175 - P(7, 8) * _tmp173 - P(8, 8) * _tmp174;
  const Scalar _tmp179 =
      _tmp71 * meas_cov(2, 0) + _tmp72 * meas_cov(0, 0) + _tmp73 * meas_cov(1, 0);
  const Scalar _tmp180 =
      _tmp71 * meas_cov(2, 1) + _tmp72 * meas_cov(0, 1) + _tmp73 * meas_cov(1, 1);
  const Scalar _tmp181 = H_theta(0, 0) * _tmp75 + H_theta(1, 0) * _tmp77 + H_theta(2, 0) * _tmp76;
  const Scalar _tmp182 = H_theta(0, 2) * _tmp75 + H_theta(1, 2) * _tmp77 + H_theta(2, 2) * _tmp76;
  const Scalar _tmp183 =
      -H_theta(0, 1) * _tmp75 - H_theta(1, 1) * _tmp77 - H_theta(2, 1) * _tmp76 + 1;
  const Scalar _tmp184 = -P(6, 6) * _tmp181 + P(7, 6) * _tmp183 - P(8, 6) * _tmp182;
  const Scalar _tmp185 = -P(6, 8) * _tmp181 + P(7, 8) * _tmp183 - P(8, 8) * _tmp182;
  const Scalar _tmp186 = -P(6, 7) * _tmp181 + P(7, 7) * _tmp183 - P(8, 7) * _tmp182;
  const Scalar _tmp187 =
      _tmp75 * meas_cov(0, 1) + _tmp76 * meas_cov(2, 1) + _tmp77 * meas_cov(1, 1);
  const Scalar _tmp188 =
      _tmp75 * meas_cov(0, 2) + _tmp76 * meas_cov(2, 2) + _tmp77 * meas_cov(1, 2);
  const Scalar _tmp189 =
      _tmp75 * meas_cov(0, 0) + _tmp76 * meas_cov(2, 0) + _tmp77 * meas_cov(1, 0);
  const Scalar _tmp190 =
      _tmp79 * meas_cov(1, 2) + _tmp80 * meas_cov(0, 2) + _tmp81 * meas_cov(2, 2);
  const Scalar _tmp191 = H_theta(0, 1) * _tmp80 + H_theta(1, 1) * _tmp79 + H_theta(2, 1) * _tmp81;
  const Scalar _tmp192 = H_theta(0, 0) * _tmp80 + H_theta(1, 0) * _tmp79 + H_theta(2, 0) * _tmp81;
  const Scalar _tmp193 =
      -H_theta(0, 2) * _tmp80 - H_theta(1, 2) * _tmp79 - H_theta(2, 2) * _tmp81 + 1;
  const Scalar _tmp194 = -P(6, 6) * _tmp192 - P(7, 6) * _tmp191 + P(8, 6) * _tmp193;
  const Scalar _tmp195 = -P(6, 8) * _tmp192 - P(7, 8) * _tmp191 + P(8, 8) * _tmp193;
  const Scalar _tmp196 = -P(6, 7) * _tmp192 - P(7, 7) * _tmp191 + P(8, 7) * _tmp193;
  const Scalar _tmp197 =
      _tmp79 * meas_cov(1, 1) + _tmp80 * meas_cov(0, 1) + _tmp81 * meas_cov(2, 1);
  const Scalar _tmp198 =
      _tmp79 * meas_cov(1, 0) + _tmp80 * meas_cov(0, 0) + _tmp81 * meas_cov(2, 0);
  const Scalar _tmp199 = H_theta(0, 2) * _tmp87 + H_theta(1, 2) * _tmp86 + H_theta(2, 2) * _tmp85;
  const Scalar _tmp200 = H_theta(0, 1) * _tmp87 + H_theta(1, 1) * _tmp86 + H_theta(2, 1) * _tmp85;
  const Scalar _tmp201 = H_theta(0, 0) * _tmp87 + H_theta(1, 0) * _tmp86 + H_theta(2, 0) * _tmp85;
  const Scalar _tmp202 =
      _tmp85 * meas_cov(2, 2) + _tmp86 * meas_cov(1, 2) + _tmp87 * meas_cov(0, 2);
  const Scalar _tmp203 =
      _tmp85 * meas_cov(2, 1) + _tmp86 * meas_cov(1, 1) + _tmp87 * meas_cov(0, 1);
  const Scalar _tmp204 =
      _tmp85 * meas_cov(2, 0) + _tmp86 * meas_cov(1, 0) + _tmp87 * meas_cov(0, 0);
  const Scalar _tmp205 = -P(6, 6) * _tmp201 - P(7, 6) * _tmp200 - P(8, 6) * _tmp199 + P(9, 6);
  const Scalar _tmp206 = -P(6, 8) * _tmp201 - P(7, 8) * _tmp200 - P(8, 8) * _tmp199 + P(9, 8);
  const Scalar _tmp207 = -P(6, 7) * _tmp201 - P(7, 7) * _tmp200 - P(8, 7) * _tmp199 + P(9, 7);
  const Scalar _tmp208 = H_theta(0, 0) * _tmp93 + H_theta(1, 0) * _tmp92 + H_theta(2, 0) * _tmp91;
  const Scalar _tmp209 = H_theta(0, 1) * _tmp93 + H_theta(1, 1) * _tmp92 + H_theta(2, 1) * _tmp91;
  const Scalar _tmp210 = H_theta(0, 2) * _tmp93 + H_theta(1, 2) * _tmp92 + H_theta(2, 2) * _tmp91;
  const Scalar _tmp211 = P(10, 7) - P(6, 7) * _tmp208 - P(7, 7) * _tmp209 - P(8, 7) * _tmp210;
  const Scalar _tmp212 = P(10, 6) - P(6, 6) * _tmp208 - P(7, 6) * _tmp209 - P(8, 6) * _tmp210;
  const Scalar _tmp213 = P(10, 8) - P(6, 8) * _tmp208 - P(7, 8) * _tmp209 - P(8, 8) * _tmp210;
  const Scalar _tmp214 =
      _tmp91 * meas_cov(2, 1) + _tmp92 * meas_cov(1, 1) + _tmp93 * meas_cov(0, 1);
  const Scalar _tmp215 =
      _tmp91 * meas_cov(2, 2) + _tmp92 * meas_cov(1, 2) + _tmp93 * meas_cov(0, 2);
  const Scalar _tmp216 =
      _tmp91 * meas_cov(2, 0) + _tmp92 * meas_cov(1, 0) + _tmp93 * meas_cov(0, 0);
  const Scalar _tmp217 = H_theta(0, 1) * _tmp97 + H_theta(1, 1) * _tmp99 + H_theta(2, 1) * _tmp98;
  const Scalar _tmp218 = H_theta(0, 2) * _tmp97 + H_theta(1, 2) * _tmp99 + H_theta(2, 2) * _tmp98;
  const Scalar _tmp219 = H_theta(0, 0) * _tmp97 + H_theta(1, 0) * _tmp99 + H_theta(2, 0) * _tmp98;
  const Scalar _tmp220 =
      _tmp97 * meas_cov(0, 2) + _tmp98 * meas_cov(2, 2) + _tmp99 * meas_cov(1, 2);
  const Scalar _tmp221 =
      _tmp97 * meas_cov(0, 0) + _tmp98 * meas_cov(2, 0) + _tmp99 * meas_cov(1, 0);
  const Scalar _tmp222 =
      _tmp97 * meas_cov(0, 1) + _tmp98 * meas_cov(2, 1) + _tmp99 * meas_cov(1, 1);
  const Scalar _tmp223 = P(11, 6) - P(6, 6) * _tmp219 - P(7, 6) * _tmp217 - P(8, 6) * _tmp218;
  const Scalar _tmp224 = P(11, 7) - P(6, 7) * _tmp219 - P(7, 7) * _tmp217 - P(8, 7) * _tmp218;
  const Scalar _tmp225 = P(11, 8) - P(6, 8) * _tmp219 - P(7, 8) * _tmp217 - P(8, 8) * _tmp218;
  const Scalar _tmp226 =
      H_theta(0, 0) * _tmp103 + H_theta(1, 0) * _tmp104 + H_theta(2, 0) * _tmp105;
  const Scalar _tmp227 =
      H_theta(0, 1) * _tmp103 + H_theta(1, 1) * _tmp104 + H_theta(2, 1) * _tmp105;
  const Scalar _tmp228 =
      H_theta(0, 2) * _tmp103 + H_theta(1, 2) * _tmp104 + H_theta(2, 2) * _tmp105;
  const Scalar _tmp229 = P(12, 7) - P(6, 7) * _tmp226 - P(7, 7) * _tmp227 - P(8, 7) * _tmp228;
  const Scalar _tmp230 = P(12, 8) - P(6, 8) * _tmp226 - P(7, 8) * _tmp227 - P(8, 8) * _tmp228;
  const Scalar _tmp231 = P(12, 6) - P(6, 6) * _tmp226 - P(7, 6) * _tmp227 - P(8, 6) * _tmp228;
  const Scalar _tmp232 =
      _tmp103 * meas_cov(0, 1) + _tmp104 * meas_cov(1, 1) + _tmp105 * meas_cov(2, 1);
  const Scalar _tmp233 =
      _tmp103 * meas_cov(0, 2) + _tmp104 * meas_cov(1, 2) + _tmp105 * meas_cov(2, 2);
  const Scalar _tmp234 =
      _tmp103 * meas_cov(0, 0) + _tmp104 * meas_cov(1, 0) + _tmp105 * meas_cov(2, 0);
  const Scalar _tmp235 =
      H_theta(0, 0) * _tmp111 + H_theta(1, 0) * _tmp109 + H_theta(2, 0) * _tmp110;
  const Scalar _tmp236 =
      H_theta(0, 1) * _tmp111 + H_theta(1, 1) * _tmp109 + H_theta(2, 1) * _tmp110;
  const Scalar _tmp237 =
      H_theta(0, 2) * _tmp111 + H_theta(1, 2) * _tmp109 + H_theta(2, 2) * _tmp110;
  const Scalar _tmp238 =
      _tmp109 * meas_cov(1, 0) + _tmp110 * meas_cov(2, 0) + _tmp111 * meas_cov(0, 0);
  const Scalar _tmp239 =
      _tmp109 * meas_cov(1, 2) + _tmp110 * meas_cov(2, 2) + _tmp111 * meas_cov(0, 2);
  const Scalar _tmp240 = P(13, 7) - P(6, 7) * _tmp235 - P(7, 7) * _tmp236 - P(8, 7) * _tmp237;
  const Scalar _tmp241 = P(13, 8) - P(6, 8) * _tmp235 - P(7, 8) * _tmp236 - P(8, 8) * _tmp237;
  const Scalar _tmp242 = P(13, 6) - P(6, 6) * _tmp235 - P(7, 6) * _tmp236 - P(8, 6) * _tmp237;
  const Scalar _tmp243 =
      _tmp109 * meas_cov(1, 1) + _tmp110 * meas_cov(2, 1) + _tmp111 * meas_cov(0, 1);
  const Scalar _tmp244 =
      _tmp115 * meas_cov(2, 0) + _tmp116 * meas_cov(0, 0) + _tmp117 * meas_cov(1, 0);
  const Scalar _tmp245 =
      H_theta(0, 0) * _tmp116 + H_theta(1, 0) * _tmp117 + H_theta(2, 0) * _tmp115;
  const Scalar _tmp246 =
      H_theta(0, 2) * _tmp116 + H_theta(1, 2) * _tmp117 + H_theta(2, 2) * _tmp115;
  const Scalar _tmp247 =
      H_theta(0, 1) * _tmp116 + H_theta(1, 1) * _tmp117 + H_theta(2, 1) * _tmp115;
  const Scalar _tmp248 = P(14, 8) - P(6, 8) * _tmp245 - P(7, 8) * _tmp247 - P(8, 8) * _tmp246;
  const Scalar _tmp249 = P(14, 7) - P(6, 7) * _tmp245 - P(7, 7) * _tmp247 - P(8, 7) * _tmp246;
  const Scalar _tmp250 = P(14, 6) - P(6, 6) * _tmp245 - P(7, 6) * _tmp247 - P(8, 6) * _tmp246;
  const Scalar _tmp251 =
      _tmp115 * meas_cov(2, 2) + _tmp116 * meas_cov(0, 2) + _tmp117 * meas_cov(1, 2);
  const Scalar _tmp252 =
      _tmp115 * meas_cov(2, 1) + _tmp116 * meas_cov(0, 1) + _tmp117 * meas_cov(1, 1);

  // Output terms (3)
  if (error_state != nullptr) {
    Eigen::Matrix<Scalar, 15, 1>& _error_state = (*error_state);

    _error_state(0, 0) = _tmp32 * innov(2, 0) + _tmp36 * innov(0, 0) + _tmp39 * innov(1, 0);
    _error_state(1, 0) = _tmp43 * innov(0, 0) + _tmp44 * innov(2, 0) + _tmp45 * innov(1, 0);
    _error_state(2, 0) = _tmp49 * innov(1, 0) + _tmp50 * innov(0, 0) + _tmp51 * innov(2, 0);
    _error_state(3, 0) = _tmp55 * innov(2, 0) + _tmp56 * innov(1, 0) + _tmp57 * innov(0, 0);
    _error_state(4, 0) = _tmp61 * innov(2, 0) + _tmp62 * innov(0, 0) + _tmp63 * innov(1, 0);
    _error_state(5, 0) = _tmp67 * innov(2, 0) + _tmp68 * innov(1, 0) + _tmp69 * innov(0, 0);
    _error_state(6, 0) = _tmp71 * innov(2, 0) + _tmp72 * innov(0, 0) + _tmp73 * innov(1, 0);
    _error_state(7, 0) = _tmp75 * innov(0, 0) + _tmp76 * innov(2, 0) + _tmp77 * innov(1, 0);
    _error_state(8, 0) = _tmp79 * innov(1, 0) + _tmp80 * innov(0, 0) + _tmp81 * innov(2, 0);
    _error_state(9, 0) = _tmp85 * innov(2, 0) + _tmp86 * innov(1, 0) + _tmp87 * innov(0, 0);
    _error_state(10, 0) = _tmp91 * innov(2, 0) + _tmp92 * innov(1, 0) + _tmp93 * innov(0, 0);
    _error_state(11, 0) = _tmp97 * innov(0, 0) + _tmp98 * innov(2, 0) + _tmp99 * innov(1, 0);
    _error_state(12, 0) = _tmp103 * innov(0, 0) + _tmp104 * innov(1, 0) + _tmp105 * innov(2, 0);
    _error_state(13, 0) = _tmp109 * innov(1, 0) + _tmp110 * innov(2, 0) + _tmp111 * innov(0, 0);
    _error_state(14, 0) = _tmp115 * innov(2, 0) + _tmp116 * innov(0, 0) + _tmp117 * innov(1, 0);
  }

  if (P_updated != nullptr) {
    Eigen::Matrix<Scalar, 15, 15>& _P_updated = (*P_updated);

    _P_updated(0, 0) = P(0, 0) - P(6, 0) * _tmp121 - P(7, 0) * _tmp122 - P(8, 0) * _tmp123 +
                       _tmp118 * _tmp39 + _tmp119 * _tmp36 + _tmp120 * _tmp32 - _tmp121 * _tmp126 -
                       _tmp122 * _tmp124 - _tmp123 * _tmp125;
    _P_updated(1, 0) = P(1, 0) - P(6, 0) * _tmp132 - P(7, 0) * _tmp131 - P(8, 0) * _tmp130 -
                       _tmp121 * _tmp135 - _tmp122 * _tmp134 - _tmp123 * _tmp133 +
                       _tmp127 * _tmp32 + _tmp128 * _tmp36 + _tmp129 * _tmp39;
    _P_updated(2, 0) = P(2, 0) - P(6, 0) * _tmp138 - P(7, 0) * _tmp136 - P(8, 0) * _tmp137 -
                       _tmp121 * _tmp142 - _tmp122 * _tmp140 - _tmp123 * _tmp141 +
                       _tmp139 * _tmp39 + _tmp143 * _tmp36 + _tmp144 * _tmp32;
    _P_updated(3, 0) = P(3, 0) - P(6, 0) * _tmp146 - P(7, 0) * _tmp147 - P(8, 0) * _tmp148 -
                       _tmp121 * _tmp149 - _tmp122 * _tmp150 - _tmp123 * _tmp151 +
                       _tmp145 * _tmp39 + _tmp152 * _tmp32 + _tmp153 * _tmp36;
    _P_updated(4, 0) = P(4, 0) - P(6, 0) * _tmp154 - P(7, 0) * _tmp155 - P(8, 0) * _tmp156 -
                       _tmp121 * _tmp160 - _tmp122 * _tmp159 - _tmp123 * _tmp161 +
                       _tmp157 * _tmp32 + _tmp158 * _tmp39 + _tmp162 * _tmp36;
    _P_updated(5, 0) = P(5, 0) - P(6, 0) * _tmp165 - P(7, 0) * _tmp164 - P(8, 0) * _tmp166 -
                       _tmp121 * _tmp170 - _tmp122 * _tmp169 - _tmp123 * _tmp168 +
                       _tmp163 * _tmp32 + _tmp167 * _tmp36 + _tmp171 * _tmp39;
    _P_updated(6, 0) = P(6, 0) * _tmp175 - P(7, 0) * _tmp173 - P(8, 0) * _tmp174 -
                       _tmp121 * _tmp176 - _tmp122 * _tmp177 - _tmp123 * _tmp178 +
                       _tmp172 * _tmp32 + _tmp179 * _tmp36 + _tmp180 * _tmp39;
    _P_updated(7, 0) = -P(6, 0) * _tmp181 + P(7, 0) * _tmp183 - P(8, 0) * _tmp182 -
                       _tmp121 * _tmp184 - _tmp122 * _tmp186 - _tmp123 * _tmp185 +
                       _tmp187 * _tmp39 + _tmp188 * _tmp32 + _tmp189 * _tmp36;
    _P_updated(8, 0) = -P(6, 0) * _tmp192 - P(7, 0) * _tmp191 + P(8, 0) * _tmp193 -
                       _tmp121 * _tmp194 - _tmp122 * _tmp196 - _tmp123 * _tmp195 +
                       _tmp190 * _tmp32 + _tmp197 * _tmp39 + _tmp198 * _tmp36;
    _P_updated(9, 0) = -P(6, 0) * _tmp201 - P(7, 0) * _tmp200 - P(8, 0) * _tmp199 + P(9, 0) -
                       _tmp121 * _tmp205 - _tmp122 * _tmp207 - _tmp123 * _tmp206 +
                       _tmp202 * _tmp32 + _tmp203 * _tmp39 + _tmp204 * _tmp36;
    _P_updated(10, 0) = P(10, 0) - P(6, 0) * _tmp208 - P(7, 0) * _tmp209 - P(8, 0) * _tmp210 -
                        _tmp121 * _tmp212 - _tmp122 * _tmp211 - _tmp123 * _tmp213 +
                        _tmp214 * _tmp39 + _tmp215 * _tmp32 + _tmp216 * _tmp36;
    _P_updated(11, 0) = P(11, 0) - P(6, 0) * _tmp219 - P(7, 0) * _tmp217 - P(8, 0) * _tmp218 -
                        _tmp121 * _tmp223 - _tmp122 * _tmp224 - _tmp123 * _tmp225 +
                        _tmp220 * _tmp32 + _tmp221 * _tmp36 + _tmp222 * _tmp39;
    _P_updated(12, 0) = P(12, 0) - P(6, 0) * _tmp226 - P(7, 0) * _tmp227 - P(8, 0) * _tmp228 -
                        _tmp121 * _tmp231 - _tmp122 * _tmp229 - _tmp123 * _tmp230 +
                        _tmp232 * _tmp39 + _tmp233 * _tmp32 + _tmp234 * _tmp36;
    _P_updated(13, 0) = P(13, 0) - P(6, 0) * _tmp235 - P(7, 0) * _tmp236 - P(8, 0) * _tmp237 -
                        _tmp121 * _tmp242 - _tmp122 * _tmp240 - _tmp123 * _tmp241 +
                        _tmp238 * _tmp36 + _tmp239 * _tmp32 + _tmp243 * _tmp39;
    _P_updated(14, 0) = P(14, 0) - P(6, 0) * _tmp245 - P(7, 0) * _tmp247 - P(8, 0) * _tmp246 -
                        _tmp121 * _tmp250 - _tmp122 * _tmp249 - _tmp123 * _tmp248 +
                        _tmp244 * _tmp36 + _tmp251 * _tmp32 + _tmp252 * _tmp39;
    _P_updated(0, 1) = P(0, 1) - P(6, 1) * _tmp121 - P(7, 1) * _tmp122 - P(8, 1) * _tmp123 +
                       _tmp118 * _tmp45 + _tmp119 * _tmp43 + _tmp120 * _tmp44 - _tmp124 * _tmp131 -
                       _tmp125 * _tmp130 - _tmp126 * _tmp132;
    _P_updated(1, 1) = P(1, 1) - P(6, 1) * _tmp132 - P(7, 1) * _tmp131 - P(8, 1) * _tmp130 +
                       _tmp127 * _tmp44 + _tmp128 * _tmp43 + _tmp129 * _tmp45 - _tmp130 * _tmp133 -
                       _tmp131 * _tmp134 - _tmp132 * _tmp135;
    _P_updated(2, 1) = P(2, 1) - P(6, 1) * _tmp138 - P(7, 1) * _tmp136 - P(8, 1) * _tmp137 -
                       _tmp130 * _tmp141 - _tmp131 * _tmp140 - _tmp132 * _tmp142 +
                       _tmp139 * _tmp45 + _tmp143 * _tmp43 + _tmp144 * _tmp44;
    _P_updated(3, 1) = P(3, 1) - P(6, 1) * _tmp146 - P(7, 1) * _tmp147 - P(8, 1) * _tmp148 -
                       _tmp130 * _tmp151 - _tmp131 * _tmp150 - _tmp132 * _tmp149 +
                       _tmp145 * _tmp45 + _tmp152 * _tmp44 + _tmp153 * _tmp43;
    _P_updated(4, 1) = P(4, 1) - P(6, 1) * _tmp154 - P(7, 1) * _tmp155 - P(8, 1) * _tmp156 -
                       _tmp130 * _tmp161 - _tmp131 * _tmp159 - _tmp132 * _tmp160 +
                       _tmp157 * _tmp44 + _tmp158 * _tmp45 + _tmp162 * _tmp43;
    _P_updated(5, 1) = P(5, 1) - P(6, 1) * _tmp165 - P(7, 1) * _tmp164 - P(8, 1) * _tmp166 -
                       _tmp130 * _tmp168 - _tmp131 * _tmp169 - _tmp132 * _tmp170 +
                       _tmp163 * _tmp44 + _tmp167 * _tmp43 + _tmp171 * _tmp45;
    _P_updated(6, 1) = P(6, 1) * _tmp175 - P(7, 1) * _tmp173 - P(8, 1) * _tmp174 -
                       _tmp130 * _tmp178 - _tmp131 * _tmp177 - _tmp132 * _tmp176 +
                       _tmp172 * _tmp44 + _tmp179 * _tmp43 + _tmp180 * _tmp45;
    _P_updated(7, 1) = -P(6, 1) * _tmp181 + P(7, 1) * _tmp183 - P(8, 1) * _tmp182 -
                       _tmp130 * _tmp185 - _tmp131 * _tmp186 - _tmp132 * _tmp184 +
                       _tmp187 * _tmp45 + _tmp188 * _tmp44 + _tmp189 * _tmp43;
    _P_updated(8, 1) = -P(6, 1) * _tmp192 - P(7, 1) * _tmp191 + P(8, 1) * _tmp193 -
                       _tmp130 * _tmp195 - _tmp131 * _tmp196 - _tmp132 * _tmp194 +
                       _tmp190 * _tmp44 + _tmp197 * _tmp45 + _tmp198 * _tmp43;
    _P_updated(9, 1) = -P(6, 1) * _tmp201 - P(7, 1) * _tmp200 - P(8, 1) * _tmp199 + P(9, 1) -
                       _tmp130 * _tmp206 - _tmp131 * _tmp207 - _tmp132 * _tmp205 +
                       _tmp202 * _tmp44 + _tmp203 * _tmp45 + _tmp204 * _tmp43;
    _P_updated(10, 1) = P(10, 1) - P(6, 1) * _tmp208 - P(7, 1) * _tmp209 - P(8, 1) * _tmp210 -
                        _tmp130 * _tmp213 - _tmp131 * _tmp211 - _tmp132 * _tmp212 +
                        _tmp214 * _tmp45 + _tmp215 * _tmp44 + _tmp216 * _tmp43;
    _P_updated(11, 1) = P(11, 1) - P(6, 1) * _tmp219 - P(7, 1) * _tmp217 - P(8, 1) * _tmp218 -
                        _tmp130 * _tmp225 - _tmp131 * _tmp224 - _tmp132 * _tmp223 +
                        _tmp220 * _tmp44 + _tmp221 * _tmp43 + _tmp222 * _tmp45;
    _P_updated(12, 1) = P(12, 1) - P(6, 1) * _tmp226 - P(7, 1) * _tmp227 - P(8, 1) * _tmp228 -
                        _tmp130 * _tmp230 - _tmp131 * _tmp229 - _tmp132 * _tmp231 +
                        _tmp232 * _tmp45 + _tmp233 * _tmp44 + _tmp234 * _tmp43;
    _P_updated(13, 1) = P(13, 1) - P(6, 1) * _tmp235 - P(7, 1) * _tmp236 - P(8, 1) * _tmp237 -
                        _tmp130 * _tmp241 - _tmp131 * _tmp240 - _tmp132 * _tmp242 +
                        _tmp238 * _tmp43 + _tmp239 * _tmp44 + _tmp243 * _tmp45;
    _P_updated(14, 1) = P(14, 1) - P(6, 1) * _tmp245 - P(7, 1) * _tmp247 - P(8, 1) * _tmp246 -
                        _tmp130 * _tmp248 - _tmp131 * _tmp249 - _tmp132 * _tmp250 +
                        _tmp244 * _tmp43 + _tmp251 * _tmp44 + _tmp252 * _tmp45;
    _P_updated(0, 2) = P(0, 2) - P(6, 2) * _tmp121 - P(7, 2) * _tmp122 - P(8, 2) * _tmp123 +
                       _tmp118 * _tmp49 + _tmp119 * _tmp50 + _tmp120 * _tmp51 - _tmp124 * _tmp136 -
                       _tmp125 * _tmp137 - _tmp126 * _tmp138;
    _P_updated(1, 2) = P(1, 2) - P(6, 2) * _tmp132 - P(7, 2) * _tmp131 - P(8, 2) * _tmp130 +
                       _tmp127 * _tmp51 + _tmp128 * _tmp50 + _tmp129 * _tmp49 - _tmp133 * _tmp137 -
                       _tmp134 * _tmp136 - _tmp135 * _tmp138;
    _P_updated(2, 2) = P(2, 2) - P(6, 2) * _tmp138 - P(7, 2) * _tmp136 - P(8, 2) * _tmp137 -
                       _tmp136 * _tmp140 - _tmp137 * _tmp141 - _tmp138 * _tmp142 +
                       _tmp139 * _tmp49 + _tmp143 * _tmp50 + _tmp144 * _tmp51;
    _P_updated(3, 2) = P(3, 2) - P(6, 2) * _tmp146 - P(7, 2) * _tmp147 - P(8, 2) * _tmp148 -
                       _tmp136 * _tmp150 - _tmp137 * _tmp151 - _tmp138 * _tmp149 +
                       _tmp145 * _tmp49 + _tmp152 * _tmp51 + _tmp153 * _tmp50;
    _P_updated(4, 2) = P(4, 2) - P(6, 2) * _tmp154 - P(7, 2) * _tmp155 - P(8, 2) * _tmp156 -
                       _tmp136 * _tmp159 - _tmp137 * _tmp161 - _tmp138 * _tmp160 +
                       _tmp157 * _tmp51 + _tmp158 * _tmp49 + _tmp162 * _tmp50;
    _P_updated(5, 2) = P(5, 2) - P(6, 2) * _tmp165 - P(7, 2) * _tmp164 - P(8, 2) * _tmp166 -
                       _tmp136 * _tmp169 - _tmp137 * _tmp168 - _tmp138 * _tmp170 +
                       _tmp163 * _tmp51 + _tmp167 * _tmp50 + _tmp171 * _tmp49;
    _P_updated(6, 2) = P(6, 2) * _tmp175 - P(7, 2) * _tmp173 - P(8, 2) * _tmp174 -
                       _tmp136 * _tmp177 - _tmp137 * _tmp178 - _tmp138 * _tmp176 +
                       _tmp172 * _tmp51 + _tmp179 * _tmp50 + _tmp180 * _tmp49;
    _P_updated(7, 2) = -P(6, 2) * _tmp181 + P(7, 2) * _tmp183 - P(8, 2) * _tmp182 -
                       _tmp136 * _tmp186 - _tmp137 * _tmp185 - _tmp138 * _tmp184 +
                       _tmp187 * _tmp49 + _tmp188 * _tmp51 + _tmp189 * _tmp50;
    _P_updated(8, 2) = -P(6, 2) * _tmp192 - P(7, 2) * _tmp191 + P(8, 2) * _tmp193 -
                       _tmp136 * _tmp196 - _tmp137 * _tmp195 - _tmp138 * _tmp194 +
                       _tmp190 * _tmp51 + _tmp197 * _tmp49 + _tmp198 * _tmp50;
    _P_updated(9, 2) = -P(6, 2) * _tmp201 - P(7, 2) * _tmp200 - P(8, 2) * _tmp199 + P(9, 2) -
                       _tmp136 * _tmp207 - _tmp137 * _tmp206 - _tmp138 * _tmp205 +
                       _tmp202 * _tmp51 + _tmp203 * _tmp49 + _tmp204 * _tmp50;
    _P_updated(10, 2) = P(10, 2) - P(6, 2) * _tmp208 - P(7, 2) * _tmp209 - P(8, 2) * _tmp210 -
                        _tmp136 * _tmp211 - _tmp137 * _tmp213 - _tmp138 * _tmp212 +
                        _tmp214 * _tmp49 + _tmp215 * _tmp51 + _tmp216 * _tmp50;
    _P_updated(11, 2) = P(11, 2) - P(6, 2) * _tmp219 - P(7, 2) * _tmp217 - P(8, 2) * _tmp218 -
                        _tmp136 * _tmp224 - _tmp137 * _tmp225 - _tmp138 * _tmp223 +
                        _tmp220 * _tmp51 + _tmp221 * _tmp50 + _tmp222 * _tmp49;
    _P_updated(12, 2) = P(12, 2) - P(6, 2) * _tmp226 - P(7, 2) * _tmp227 - P(8, 2) * _tmp228 -
                        _tmp136 * _tmp229 - _tmp137 * _tmp230 - _tmp138 * _tmp231 +
                        _tmp232 * _tmp49 + _tmp233 * _tmp51 + _tmp234 * _tmp50;
    _P_updated(13, 2) = P(13, 2) - P(6, 2) * _tmp235 - P(7, 2) * _tmp236 - P(8, 2) * _tmp237 -
                        _tmp136 * _tmp240 - _tmp137 * _tmp241 - _tmp138 * _tmp242 +
                        _tmp238 * _tmp50 + _tmp239 * _tmp51 + _tmp243 * _tmp49;
    _P_updated(14, 2) = P(14, 2) - P(6, 2) * _tmp245 - P(7, 2) * _tmp247 - P(8, 2) * _tmp246 -
                        _tmp136 * _tmp249 - _tmp137 * _tmp248 - _tmp138 * _tmp250 +
                        _tmp244 * _tmp50 + _tmp251 * _tmp51 + _tmp252 * _tmp49;
    _P_updated(0, 3) = P(0, 3) - P(6, 3) * _tmp121 - P(7, 3) * _tmp122 - P(8, 3) * _tmp123 +
                       _tmp118 * _tmp56 + _tmp119 * _tmp57 + _tmp120 * _tmp55 - _tmp124 * _tmp147 -
                       _tmp125 * _tmp148 - _tmp126 * _tmp146;
    _P_updated(1, 3) = P(1, 3) - P(6, 3) * _tmp132 - P(7, 3) * _tmp131 - P(8, 3) * _tmp130 +
                       _tmp127 * _tmp55 + _tmp128 * _tmp57 + _tmp129 * _tmp56 - _tmp133 * _tmp148 -
                       _tmp134 * _tmp147 - _tmp135 * _tmp146;
    _P_updated(2, 3) = P(2, 3) - P(6, 3) * _tmp138 - P(7, 3) * _tmp136 - P(8, 3) * _tmp137 +
                       _tmp139 * _tmp56 - _tmp140 * _tmp147 - _tmp141 * _tmp148 -
                       _tmp142 * _tmp146 + _tmp143 * _tmp57 + _tmp144 * _tmp55;
    _P_updated(3, 3) = P(3, 3) - P(6, 3) * _tmp146 - P(7, 3) * _tmp147 - P(8, 3) * _tmp148 +
                       _tmp145 * _tmp56 - _tmp146 * _tmp149 - _tmp147 * _tmp150 -
                       _tmp148 * _tmp151 + _tmp152 * _tmp55 + _tmp153 * _tmp57;
    _P_updated(4, 3) = P(4, 3) - P(6, 3) * _tmp154 - P(7, 3) * _tmp155 - P(8, 3) * _tmp156 -
                       _tmp146 * _tmp160 - _tmp147 * _tmp159 - _tmp148 * _tmp161 +
                       _tmp157 * _tmp55 + _tmp158 * _tmp56 + _tmp162 * _tmp57;
    _P_updated(5, 3) = P(5, 3) - P(6, 3) * _tmp165 - P(7, 3) * _tmp164 - P(8, 3) * _tmp166 -
                       _tmp146 * _tmp170 - _tmp147 * _tmp169 - _tmp148 * _tmp168 +
                       _tmp163 * _tmp55 + _tmp167 * _tmp57 + _tmp171 * _tmp56;
    _P_updated(6, 3) = P(6, 3) * _tmp175 - P(7, 3) * _tmp173 - P(8, 3) * _tmp174 -
                       _tmp146 * _tmp176 - _tmp147 * _tmp177 - _tmp148 * _tmp178 +
                       _tmp172 * _tmp55 + _tmp179 * _tmp57 + _tmp180 * _tmp56;
    _P_updated(7, 3) = -P(6, 3) * _tmp181 + P(7, 3) * _tmp183 - P(8, 3) * _tmp182 -
                       _tmp146 * _tmp184 - _tmp147 * _tmp186 - _tmp148 * _tmp185 +
                       _tmp187 * _tmp56 + _tmp188 * _tmp55 + _tmp189 * _tmp57;
    _P_updated(8, 3) = -P(6, 3) * _tmp192 - P(7, 3) * _tmp191 + P(8, 3) * _tmp193 -
                       _tmp146 * _tmp194 - _tmp147 * _tmp196 - _tmp148 * _tmp195 +
                       _tmp190 * _tmp55 + _tmp197 * _tmp56 + _tmp198 * _tmp57;
    _P_updated(9, 3) = -P(6, 3) * _tmp201 - P(7, 3) * _tmp200 - P(8, 3) * _tmp199 + P(9, 3) -
                       _tmp146 * _tmp205 - _tmp147 * _tmp207 - _tmp148 * _tmp206 +
                       _tmp202 * _tmp55 + _tmp203 * _tmp56 + _tmp204 * _tmp57;
    _P_updated(10, 3) = P(10, 3) - P(6, 3) * _tmp208 - P(7, 3) * _tmp209 - P(8, 3) * _tmp210 -
                        _tmp146 * _tmp212 - _tmp147 * _tmp211 - _tmp148 * _tmp213 +
                        _tmp214 * _tmp56 + _tmp215 * _tmp55 + _tmp216 * _tmp57;
    _P_updated(11, 3) = P(11, 3) - P(6, 3) * _tmp219 - P(7, 3) * _tmp217 - P(8, 3) * _tmp218 -
                        _tmp146 * _tmp223 - _tmp147 * _tmp224 - _tmp148 * _tmp225 +
                        _tmp220 * _tmp55 + _tmp221 * _tmp57 + _tmp222 * _tmp56;
    _P_updated(12, 3) = P(12, 3) - P(6, 3) * _tmp226 - P(7, 3) * _tmp227 - P(8, 3) * _tmp228 -
                        _tmp146 * _tmp231 - _tmp147 * _tmp229 - _tmp148 * _tmp230 +
                        _tmp232 * _tmp56 + _tmp233 * _tmp55 + _tmp234 * _tmp57;
    _P_updated(13, 3) = P(13, 3) - P(6, 3) * _tmp235 - P(7, 3) * _tmp236 - P(8, 3) * _tmp237 -
                        _tmp146 * _tmp242 - _tmp147 * _tmp240 - _tmp148 * _tmp241 +
                        _tmp238 * _tmp57 + _tmp239 * _tmp55 + _tmp243 * _tmp56;
    _P_updated(14, 3) = P(14, 3) - P(6, 3) * _tmp245 - P(7, 3) * _tmp247 - P(8, 3) * _tmp246 -
                        _tmp146 * _tmp250 - _tmp147 * _tmp249 - _tmp148 * _tmp248 +
                        _tmp244 * _tmp57 + _tmp251 * _tmp55 + _tmp252 * _tmp56;
    _P_updated(0, 4) = P(0, 4) - P(6, 4) * _tmp121 - P(7, 4) * _tmp122 - P(8, 4) * _tmp123 +
                       _tmp118 * _tmp63 + _tmp119 * _tmp62 + _tmp120 * _tmp61 - _tmp124 * _tmp155 -
                       _tmp125 * _tmp156 - _tmp126 * _tmp154;
    _P_updated(1, 4) = P(1, 4) - P(6, 4) * _tmp132 - P(7, 4) * _tmp131 - P(8, 4) * _tmp130 +
                       _tmp127 * _tmp61 + _tmp128 * _tmp62 + _tmp129 * _tmp63 - _tmp133 * _tmp156 -
                       _tmp134 * _tmp155 - _tmp135 * _tmp154;
    _P_updated(2, 4) = P(2, 4) - P(6, 4) * _tmp138 - P(7, 4) * _tmp136 - P(8, 4) * _tmp137 +
                       _tmp139 * _tmp63 - _tmp140 * _tmp155 - _tmp141 * _tmp156 -
                       _tmp142 * _tmp154 + _tmp143 * _tmp62 + _tmp144 * _tmp61;
    _P_updated(3, 4) = P(3, 4) - P(6, 4) * _tmp146 - P(7, 4) * _tmp147 - P(8, 4) * _tmp148 +
                       _tmp145 * _tmp63 - _tmp149 * _tmp154 - _tmp150 * _tmp155 -
                       _tmp151 * _tmp156 + _tmp152 * _tmp61 + _tmp153 * _tmp62;
    _P_updated(4, 4) = P(4, 4) - P(6, 4) * _tmp154 - P(7, 4) * _tmp155 - P(8, 4) * _tmp156 -
                       _tmp154 * _tmp160 - _tmp155 * _tmp159 - _tmp156 * _tmp161 +
                       _tmp157 * _tmp61 + _tmp158 * _tmp63 + _tmp162 * _tmp62;
    _P_updated(5, 4) = P(5, 4) - P(6, 4) * _tmp165 - P(7, 4) * _tmp164 - P(8, 4) * _tmp166 -
                       _tmp154 * _tmp170 - _tmp155 * _tmp169 - _tmp156 * _tmp168 +
                       _tmp163 * _tmp61 + _tmp167 * _tmp62 + _tmp171 * _tmp63;
    _P_updated(6, 4) = P(6, 4) * _tmp175 - P(7, 4) * _tmp173 - P(8, 4) * _tmp174 -
                       _tmp154 * _tmp176 - _tmp155 * _tmp177 - _tmp156 * _tmp178 +
                       _tmp172 * _tmp61 + _tmp179 * _tmp62 + _tmp180 * _tmp63;
    _P_updated(7, 4) = -P(6, 4) * _tmp181 + P(7, 4) * _tmp183 - P(8, 4) * _tmp182 -
                       _tmp154 * _tmp184 - _tmp155 * _tmp186 - _tmp156 * _tmp185 +
                       _tmp187 * _tmp63 + _tmp188 * _tmp61 + _tmp189 * _tmp62;
    _P_updated(8, 4) = -P(6, 4) * _tmp192 - P(7, 4) * _tmp191 + P(8, 4) * _tmp193 -
                       _tmp154 * _tmp194 - _tmp155 * _tmp196 - _tmp156 * _tmp195 +
                       _tmp190 * _tmp61 + _tmp197 * _tmp63 + _tmp198 * _tmp62;
    _P_updated(9, 4) = -P(6, 4) * _tmp201 - P(7, 4) * _tmp200 - P(8, 4) * _tmp199 + P(9, 4) -
                       _tmp154 * _tmp205 - _tmp155 * _tmp207 - _tmp156 * _tmp206 +
                       _tmp202 * _tmp61 + _tmp203 * _tmp63 + _tmp204 * _tmp62;
    _P_updated(10, 4) = P(10, 4) - P(6, 4) * _tmp208 - P(7, 4) * _tmp209 - P(8, 4) * _tmp210 -
                        _tmp154 * _tmp212 - _tmp155 * _tmp211 - _tmp156 * _tmp213 +
                        _tmp214 * _tmp63 + _tmp215 * _tmp61 + _tmp216 * _tmp62;
    _P_updated(11, 4) = P(11, 4) - P(6, 4) * _tmp219 - P(7, 4) * _tmp217 - P(8, 4) * _tmp218 -
                        _tmp154 * _tmp223 - _tmp155 * _tmp224 - _tmp156 * _tmp225 +
                        _tmp220 * _tmp61 + _tmp221 * _tmp62 + _tmp222 * _tmp63;
    _P_updated(12, 4) = P(12, 4) - P(6, 4) * _tmp226 - P(7, 4) * _tmp227 - P(8, 4) * _tmp228 -
                        _tmp154 * _tmp231 - _tmp155 * _tmp229 - _tmp156 * _tmp230 +
                        _tmp232 * _tmp63 + _tmp233 * _tmp61 + _tmp234 * _tmp62;
    _P_updated(13, 4) = P(13, 4) - P(6, 4) * _tmp235 - P(7, 4) * _tmp236 - P(8, 4) * _tmp237 -
                        _tmp154 * _tmp242 - _tmp155 * _tmp240 - _tmp156 * _tmp241 +
                        _tmp238 * _tmp62 + _tmp239 * _tmp61 + _tmp243 * _tmp63;
    _P_updated(14, 4) = P(14, 4) - P(6, 4) * _tmp245 - P(7, 4) * _tmp247 - P(8, 4) * _tmp246 -
                        _tmp154 * _tmp250 - _tmp155 * _tmp249 - _tmp156 * _tmp248 +
                        _tmp244 * _tmp62 + _tmp251 * _tmp61 + _tmp252 * _tmp63;
    _P_updated(0, 5) = P(0, 5) - P(6, 5) * _tmp121 - P(7, 5) * _tmp122 - P(8, 5) * _tmp123 +
                       _tmp118 * _tmp68 + _tmp119 * _tmp69 + _tmp120 * _tmp67 - _tmp124 * _tmp164 -
                       _tmp125 * _tmp166 - _tmp126 * _tmp165;
    _P_updated(1, 5) = P(1, 5) - P(6, 5) * _tmp132 - P(7, 5) * _tmp131 - P(8, 5) * _tmp130 +
                       _tmp127 * _tmp67 + _tmp128 * _tmp69 + _tmp129 * _tmp68 - _tmp133 * _tmp166 -
                       _tmp134 * _tmp164 - _tmp135 * _tmp165;
    _P_updated(2, 5) = P(2, 5) - P(6, 5) * _tmp138 - P(7, 5) * _tmp136 - P(8, 5) * _tmp137 +
                       _tmp139 * _tmp68 - _tmp140 * _tmp164 - _tmp141 * _tmp166 -
                       _tmp142 * _tmp165 + _tmp143 * _tmp69 + _tmp144 * _tmp67;
    _P_updated(3, 5) = P(3, 5) - P(6, 5) * _tmp146 - P(7, 5) * _tmp147 - P(8, 5) * _tmp148 +
                       _tmp145 * _tmp68 - _tmp149 * _tmp165 - _tmp150 * _tmp164 -
                       _tmp151 * _tmp166 + _tmp152 * _tmp67 + _tmp153 * _tmp69;
    _P_updated(4, 5) = P(4, 5) - P(6, 5) * _tmp154 - P(7, 5) * _tmp155 - P(8, 5) * _tmp156 +
                       _tmp157 * _tmp67 + _tmp158 * _tmp68 - _tmp159 * _tmp164 - _tmp160 * _tmp165 -
                       _tmp161 * _tmp166 + _tmp162 * _tmp69;
    _P_updated(5, 5) = P(5, 5) - P(6, 5) * _tmp165 - P(7, 5) * _tmp164 - P(8, 5) * _tmp166 +
                       _tmp163 * _tmp67 - _tmp164 * _tmp169 - _tmp165 * _tmp170 -
                       _tmp166 * _tmp168 + _tmp167 * _tmp69 + _tmp171 * _tmp68;
    _P_updated(6, 5) = P(6, 5) * _tmp175 - P(7, 5) * _tmp173 - P(8, 5) * _tmp174 -
                       _tmp164 * _tmp177 - _tmp165 * _tmp176 - _tmp166 * _tmp178 +
                       _tmp172 * _tmp67 + _tmp179 * _tmp69 + _tmp180 * _tmp68;
    _P_updated(7, 5) = -P(6, 5) * _tmp181 + P(7, 5) * _tmp183 - P(8, 5) * _tmp182 -
                       _tmp164 * _tmp186 - _tmp165 * _tmp184 - _tmp166 * _tmp185 +
                       _tmp187 * _tmp68 + _tmp188 * _tmp67 + _tmp189 * _tmp69;
    _P_updated(8, 5) = -P(6, 5) * _tmp192 - P(7, 5) * _tmp191 + P(8, 5) * _tmp193 -
                       _tmp164 * _tmp196 - _tmp165 * _tmp194 - _tmp166 * _tmp195 +
                       _tmp190 * _tmp67 + _tmp197 * _tmp68 + _tmp198 * _tmp69;
    _P_updated(9, 5) = -P(6, 5) * _tmp201 - P(7, 5) * _tmp200 - P(8, 5) * _tmp199 + P(9, 5) -
                       _tmp164 * _tmp207 - _tmp165 * _tmp205 - _tmp166 * _tmp206 +
                       _tmp202 * _tmp67 + _tmp203 * _tmp68 + _tmp204 * _tmp69;
    _P_updated(10, 5) = P(10, 5) - P(6, 5) * _tmp208 - P(7, 5) * _tmp209 - P(8, 5) * _tmp210 -
                        _tmp164 * _tmp211 - _tmp165 * _tmp212 - _tmp166 * _tmp213 +
                        _tmp214 * _tmp68 + _tmp215 * _tmp67 + _tmp216 * _tmp69;
    _P_updated(11, 5) = P(11, 5) - P(6, 5) * _tmp219 - P(7, 5) * _tmp217 - P(8, 5) * _tmp218 -
                        _tmp164 * _tmp224 - _tmp165 * _tmp223 - _tmp166 * _tmp225 +
                        _tmp220 * _tmp67 + _tmp221 * _tmp69 + _tmp222 * _tmp68;
    _P_updated(12, 5) = P(12, 5) - P(6, 5) * _tmp226 - P(7, 5) * _tmp227 - P(8, 5) * _tmp228 -
                        _tmp164 * _tmp229 - _tmp165 * _tmp231 - _tmp166 * _tmp230 +
                        _tmp232 * _tmp68 + _tmp233 * _tmp67 + _tmp234 * _tmp69;
    _P_updated(13, 5) = P(13, 5) - P(6, 5) * _tmp235 - P(7, 5) * _tmp236 - P(8, 5) * _tmp237 -
                        _tmp164 * _tmp240 - _tmp165 * _tmp242 - _tmp166 * _tmp241 +
                        _tmp238 * _tmp69 + _tmp239 * _tmp67 + _tmp243 * _tmp68;
    _P_updated(14, 5) = P(14, 5) - P(6, 5) * _tmp245 - P(7, 5) * _tmp247 - P(8, 5) * _tmp246 -
                        _tmp164 * _tmp249 - _tmp165 * _tmp250 - _tmp166 * _tmp248 +
                        _tmp244 * _tmp69 + _tmp251 * _tmp67 + _tmp252 * _tmp68;
    _P_updated(0, 6) = _tmp118 * _tmp73 + _tmp119 * _tmp72 + _tmp120 * _tmp71 - _tmp124 * _tmp173 -
                       _tmp125 * _tmp174 + _tmp126 * _tmp175;
    _P_updated(1, 6) = _tmp127 * _tmp71 + _tmp128 * _tmp72 + _tmp129 * _tmp73 - _tmp133 * _tmp174 -
                       _tmp134 * _tmp173 + _tmp135 * _tmp175;
    _P_updated(2, 6) = _tmp139 * _tmp73 - _tmp140 * _tmp173 - _tmp141 * _tmp174 +
                       _tmp142 * _tmp175 + _tmp143 * _tmp72 + _tmp144 * _tmp71;
    _P_updated(3, 6) = _tmp145 * _tmp73 + _tmp149 * _tmp175 - _tmp150 * _tmp173 -
                       _tmp151 * _tmp174 + _tmp152 * _tmp71 + _tmp153 * _tmp72;
    _P_updated(4, 6) = _tmp157 * _tmp71 + _tmp158 * _tmp73 - _tmp159 * _tmp173 + _tmp160 * _tmp175 -
                       _tmp161 * _tmp174 + _tmp162 * _tmp72;
    _P_updated(5, 6) = _tmp163 * _tmp71 + _tmp167 * _tmp72 - _tmp168 * _tmp174 - _tmp169 * _tmp173 +
                       _tmp170 * _tmp175 + _tmp171 * _tmp73;
    _P_updated(6, 6) = _tmp172 * _tmp71 - _tmp173 * _tmp177 - _tmp174 * _tmp178 +
                       _tmp175 * _tmp176 + _tmp179 * _tmp72 + _tmp180 * _tmp73;
    _P_updated(7, 6) = -_tmp173 * _tmp186 - _tmp174 * _tmp185 + _tmp175 * _tmp184 +
                       _tmp187 * _tmp73 + _tmp188 * _tmp71 + _tmp189 * _tmp72;
    _P_updated(8, 6) = -_tmp173 * _tmp196 - _tmp174 * _tmp195 + _tmp175 * _tmp194 +
                       _tmp190 * _tmp71 + _tmp197 * _tmp73 + _tmp198 * _tmp72;
    _P_updated(9, 6) = -_tmp173 * _tmp207 - _tmp174 * _tmp206 + _tmp175 * _tmp205 +
                       _tmp202 * _tmp71 + _tmp203 * _tmp73 + _tmp204 * _tmp72;
    _P_updated(10, 6) = -_tmp173 * _tmp211 - _tmp174 * _tmp213 + _tmp175 * _tmp212 +
                        _tmp214 * _tmp73 + _tmp215 * _tmp71 + _tmp216 * _tmp72;
    _P_updated(11, 6) = -_tmp173 * _tmp224 - _tmp174 * _tmp225 + _tmp175 * _tmp223 +
                        _tmp220 * _tmp71 + _tmp221 * _tmp72 + _tmp222 * _tmp73;
    _P_updated(12, 6) = -_tmp173 * _tmp229 - _tmp174 * _tmp230 + _tmp175 * _tmp231 +
                        _tmp232 * _tmp73 + _tmp233 * _tmp71 + _tmp234 * _tmp72;
    _P_updated(13, 6) = -_tmp173 * _tmp240 - _tmp174 * _tmp241 + _tmp175 * _tmp242 +
                        _tmp238 * _tmp72 + _tmp239 * _tmp71 + _tmp243 * _tmp73;
    _P_updated(14, 6) = -_tmp173 * _tmp249 - _tmp174 * _tmp248 + _tmp175 * _tmp250 +
                        _tmp244 * _tmp72 + _tmp251 * _tmp71 + _tmp252 * _tmp73;
    _P_updated(0, 7) = _tmp118 * _tmp77 + _tmp119 * _tmp75 + _tmp120 * _tmp76 + _tmp124 * _tmp183 -
                       _tmp125 * _tmp182 - _tmp126 * _tmp181;
    _P_updated(1, 7) = _tmp127 * _tmp76 + _tmp128 * _tmp75 + _tmp129 * _tmp77 - _tmp133 * _tmp182 +
                       _tmp134 * _tmp183 - _tmp135 * _tmp181;
    _P_updated(2, 7) = _tmp139 * _tmp77 + _tmp140 * _tmp183 - _tmp141 * _tmp182 -
                       _tmp142 * _tmp181 + _tmp143 * _tmp75 + _tmp144 * _tmp76;
    _P_updated(3, 7) = _tmp145 * _tmp77 - _tmp149 * _tmp181 + _tmp150 * _tmp183 -
                       _tmp151 * _tmp182 + _tmp152 * _tmp76 + _tmp153 * _tmp75;
    _P_updated(4, 7) = _tmp157 * _tmp76 + _tmp158 * _tmp77 + _tmp159 * _tmp183 - _tmp160 * _tmp181 -
                       _tmp161 * _tmp182 + _tmp162 * _tmp75;
    _P_updated(5, 7) = _tmp163 * _tmp76 + _tmp167 * _tmp75 - _tmp168 * _tmp182 + _tmp169 * _tmp183 -
                       _tmp170 * _tmp181 + _tmp171 * _tmp77;
    _P_updated(6, 7) = _tmp172 * _tmp76 - _tmp176 * _tmp181 + _tmp177 * _tmp183 -
                       _tmp178 * _tmp182 + _tmp179 * _tmp75 + _tmp180 * _tmp77;
    _P_updated(7, 7) = -_tmp181 * _tmp184 - _tmp182 * _tmp185 + _tmp183 * _tmp186 +
                       _tmp187 * _tmp77 + _tmp188 * _tmp76 + _tmp189 * _tmp75;
    _P_updated(8, 7) = -_tmp181 * _tmp194 - _tmp182 * _tmp195 + _tmp183 * _tmp196 +
                       _tmp190 * _tmp76 + _tmp197 * _tmp77 + _tmp198 * _tmp75;
    _P_updated(9, 7) = -_tmp181 * _tmp205 - _tmp182 * _tmp206 + _tmp183 * _tmp207 +
                       _tmp202 * _tmp76 + _tmp203 * _tmp77 + _tmp204 * _tmp75;
    _P_updated(10, 7) = -_tmp181 * _tmp212 - _tmp182 * _tmp213 + _tmp183 * _tmp211 +
                        _tmp214 * _tmp77 + _tmp215 * _tmp76 + _tmp216 * _tmp75;
    _P_updated(11, 7) = -_tmp181 * _tmp223 - _tmp182 * _tmp225 + _tmp183 * _tmp224 +
                        _tmp220 * _tmp76 + _tmp221 * _tmp75 + _tmp222 * _tmp77;
    _P_updated(12, 7) = -_tmp181 * _tmp231 - _tmp182 * _tmp230 + _tmp183 * _tmp229 +
                        _tmp232 * _tmp77 + _tmp233 * _tmp76 + _tmp234 * _tmp75;
    _P_updated(13, 7) = -_tmp181 * _tmp242 - _tmp182 * _tmp241 + _tmp183 * _tmp240 +
                        _tmp238 * _tmp75 + _tmp239 * _tmp76 + _tmp243 * _tmp77;
    _P_updated(14, 7) = -_tmp181 * _tmp250 - _tmp182 * _tmp248 + _tmp183 * _tmp249 +
                        _tmp244 * _tmp75 + _tmp251 * _tmp76 + _tmp252 * _tmp77;
    _P_updated(0, 8) = _tmp118 * _tmp79 + _tmp119 * _tmp80 + _tmp120 * _tmp81 - _tmp124 * _tmp191 +
                       _tmp125 * _tmp193 - _tmp126 * _tmp192;
    _P_updated(1, 8) = _tmp127 * _tmp81 + _tmp128 * _tmp80 + _tmp129 * _tmp79 + _tmp133 * _tmp193 -
                       _tmp134 * _tmp191 - _tmp135 * _tmp192;
    _P_updated(2, 8) = _tmp139 * _tmp79 - _tmp140 * _tmp191 + _tmp141 * _tmp193 -
                       _tmp142 * _tmp192 + _tmp143 * _tmp80 + _tmp144 * _tmp81;
    _P_updated(3, 8) = _tmp145 * _tmp79 - _tmp149 * _tmp192 - _tmp150 * _tmp191 +
                       _tmp151 * _tmp193 + _tmp152 * _tmp81 + _tmp153 * _tmp80;
    _P_updated(4, 8) = _tmp157 * _tmp81 + _tmp158 * _tmp79 - _tmp159 * _tmp191 - _tmp160 * _tmp192 +
                       _tmp161 * _tmp193 + _tmp162 * _tmp80;
    _P_updated(5, 8) = _tmp163 * _tmp81 + _tmp167 * _tmp80 + _tmp168 * _tmp193 - _tmp169 * _tmp191 -
                       _tmp170 * _tmp192 + _tmp171 * _tmp79;
    _P_updated(6, 8) = _tmp172 * _tmp81 - _tmp176 * _tmp192 - _tmp177 * _tmp191 +
                       _tmp178 * _tmp193 + _tmp179 * _tmp80 + _tmp180 * _tmp79;
    _P_updated(7, 8) = -_tmp184 * _tmp192 + _tmp185 * _tmp193 - _tmp186 * _tmp191 +
                       _tmp187 * _tmp79 + _tmp188 * _tmp81 + _tmp189 * _tmp80;
    _P_updated(8, 8) = _tmp190 * _tmp81 - _tmp191 * _tmp196 - _tmp192 * _tmp194 +
                       _tmp193 * _tmp195 + _tmp197 * _tmp79 + _tmp198 * _tmp80;
    _P_updated(9, 8) = -_tmp191 * _tmp207 - _tmp192 * _tmp205 + _tmp193 * _tmp206 +
                       _tmp202 * _tmp81 + _tmp203 * _tmp79 + _tmp204 * _tmp80;
    _P_updated(10, 8) = -_tmp191 * _tmp211 - _tmp192 * _tmp212 + _tmp193 * _tmp213 +
                        _tmp214 * _tmp79 + _tmp215 * _tmp81 + _tmp216 * _tmp80;
    _P_updated(11, 8) = -_tmp191 * _tmp224 - _tmp192 * _tmp223 + _tmp193 * _tmp225 +
                        _tmp220 * _tmp81 + _tmp221 * _tmp80 + _tmp222 * _tmp79;
    _P_updated(12, 8) = -_tmp191 * _tmp229 - _tmp192 * _tmp231 + _tmp193 * _tmp230 +
                        _tmp232 * _tmp79 + _tmp233 * _tmp81 + _tmp234 * _tmp80;
    _P_updated(13, 8) = -_tmp191 * _tmp240 - _tmp192 * _tmp242 + _tmp193 * _tmp241 +
                        _tmp238 * _tmp80 + _tmp239 * _tmp81 + _tmp243 * _tmp79;
    _P_updated(14, 8) = -_tmp191 * _tmp249 - _tmp192 * _tmp250 + _tmp193 * _tmp248 +
                        _tmp244 * _tmp80 + _tmp251 * _tmp81 + _tmp252 * _tmp79;
    _P_updated(0, 9) = P(0, 9) - P(6, 9) * _tmp121 - P(7, 9) * _tmp122 - P(8, 9) * _tmp123 +
                       _tmp118 * _tmp86 + _tmp119 * _tmp87 + _tmp120 * _tmp85 - _tmp124 * _tmp200 -
                       _tmp125 * _tmp199 - _tmp126 * _tmp201;
    _P_updated(1, 9) = P(1, 9) - P(6, 9) * _tmp132 - P(7, 9) * _tmp131 - P(8, 9) * _tmp130 +
                       _tmp127 * _tmp85 + _tmp128 * _tmp87 + _tmp129 * _tmp86 - _tmp133 * _tmp199 -
                       _tmp134 * _tmp200 - _tmp135 * _tmp201;
    _P_updated(2, 9) = P(2, 9) - P(6, 9) * _tmp138 - P(7, 9) * _tmp136 - P(8, 9) * _tmp137 +
                       _tmp139 * _tmp86 - _tmp140 * _tmp200 - _tmp141 * _tmp199 -
                       _tmp142 * _tmp201 + _tmp143 * _tmp87 + _tmp144 * _tmp85;
    _P_updated(3, 9) = P(3, 9) - P(6, 9) * _tmp146 - P(7, 9) * _tmp147 - P(8, 9) * _tmp148 +
                       _tmp145 * _tmp86 - _tmp149 * _tmp201 - _tmp150 * _tmp200 -
                       _tmp151 * _tmp199 + _tmp152 * _tmp85 + _tmp153 * _tmp87;
    _P_updated(4, 9) = P(4, 9) - P(6, 9) * _tmp154 - P(7, 9) * _tmp155 - P(8, 9) * _tmp156 +
                       _tmp157 * _tmp85 + _tmp158 * _tmp86 - _tmp159 * _tmp200 - _tmp160 * _tmp201 -
                       _tmp161 * _tmp199 + _tmp162 * _tmp87;
    _P_updated(5, 9) = P(5, 9) - P(6, 9) * _tmp165 - P(7, 9) * _tmp164 - P(8, 9) * _tmp166 +
                       _tmp163 * _tmp85 + _tmp167 * _tmp87 - _tmp168 * _tmp199 - _tmp169 * _tmp200 -
                       _tmp170 * _tmp201 + _tmp171 * _tmp86;
    _P_updated(6, 9) = P(6, 9) * _tmp175 - P(7, 9) * _tmp173 - P(8, 9) * _tmp174 +
                       _tmp172 * _tmp85 - _tmp176 * _tmp201 - _tmp177 * _tmp200 -
                       _tmp178 * _tmp199 + _tmp179 * _tmp87 + _tmp180 * _tmp86;
    _P_updated(7, 9) = -P(6, 9) * _tmp181 + P(7, 9) * _tmp183 - P(8, 9) * _tmp182 -
                       _tmp184 * _tmp201 - _tmp185 * _tmp199 - _tmp186 * _tmp200 +
                       _tmp187 * _tmp86 + _tmp188 * _tmp85 + _tmp189 * _tmp87;
    _P_updated(8, 9) = -P(6, 9) * _tmp192 - P(7, 9) * _tmp191 + P(8, 9) * _tmp193 +
                       _tmp190 * _tmp85 - _tmp194 * _tmp201 - _tmp195 * _tmp199 -
                       _tmp196 * _tmp200 + _tmp197 * _tmp86 + _tmp198 * _tmp87;
    _P_updated(9, 9) = -P(6, 9) * _tmp201 - P(7, 9) * _tmp200 - P(8, 9) * _tmp199 + P(9, 9) -
                       _tmp199 * _tmp206 - _tmp200 * _tmp207 - _tmp201 * _tmp205 +
                       _tmp202 * _tmp85 + _tmp203 * _tmp86 + _tmp204 * _tmp87;
    _P_updated(10, 9) = P(10, 9) - P(6, 9) * _tmp208 - P(7, 9) * _tmp209 - P(8, 9) * _tmp210 -
                        _tmp199 * _tmp213 - _tmp200 * _tmp211 - _tmp201 * _tmp212 +
                        _tmp214 * _tmp86 + _tmp215 * _tmp85 + _tmp216 * _tmp87;
    _P_updated(11, 9) = P(11, 9) - P(6, 9) * _tmp219 - P(7, 9) * _tmp217 - P(8, 9) * _tmp218 -
                        _tmp199 * _tmp225 - _tmp200 * _tmp224 - _tmp201 * _tmp223 +
                        _tmp220 * _tmp85 + _tmp221 * _tmp87 + _tmp222 * _tmp86;
    _P_updated(12, 9) = P(12, 9) - P(6, 9) * _tmp226 - P(7, 9) * _tmp227 - P(8, 9) * _tmp228 -
                        _tmp199 * _tmp230 - _tmp200 * _tmp229 - _tmp201 * _tmp231 +
                        _tmp232 * _tmp86 + _tmp233 * _tmp85 + _tmp234 * _tmp87;
    _P_updated(13, 9) = P(13, 9) - P(6, 9) * _tmp235 - P(7, 9) * _tmp236 - P(8, 9) * _tmp237 -
                        _tmp199 * _tmp241 - _tmp200 * _tmp240 - _tmp201 * _tmp242 +
                        _tmp238 * _tmp87 + _tmp239 * _tmp85 + _tmp243 * _tmp86;
    _P_updated(14, 9) = P(14, 9) - P(6, 9) * _tmp245 - P(7, 9) * _tmp247 - P(8, 9) * _tmp246 -
                        _tmp199 * _tmp248 - _tmp200 * _tmp249 - _tmp201 * _tmp250 +
                        _tmp244 * _tmp87 + _tmp251 * _tmp85 + _tmp252 * _tmp86;
    _P_updated(0, 10) = P(0, 10) - P(6, 10) * _tmp121 - P(7, 10) * _tmp122 - P(8, 10) * _tmp123 +
                        _tmp118 * _tmp92 + _tmp119 * _tmp93 + _tmp120 * _tmp91 - _tmp124 * _tmp209 -
                        _tmp125 * _tmp210 - _tmp126 * _tmp208;
    _P_updated(1, 10) = P(1, 10) - P(6, 10) * _tmp132 - P(7, 10) * _tmp131 - P(8, 10) * _tmp130 +
                        _tmp127 * _tmp91 + _tmp128 * _tmp93 + _tmp129 * _tmp92 - _tmp133 * _tmp210 -
                        _tmp134 * _tmp209 - _tmp135 * _tmp208;
    _P_updated(2, 10) = P(2, 10) - P(6, 10) * _tmp138 - P(7, 10) * _tmp136 - P(8, 10) * _tmp137 +
                        _tmp139 * _tmp92 - _tmp140 * _tmp209 - _tmp141 * _tmp210 -
                        _tmp142 * _tmp208 + _tmp143 * _tmp93 + _tmp144 * _tmp91;
    _P_updated(3, 10) = P(3, 10) - P(6, 10) * _tmp146 - P(7, 10) * _tmp147 - P(8, 10) * _tmp148 +
                        _tmp145 * _tmp92 - _tmp149 * _tmp208 - _tmp150 * _tmp209 -
                        _tmp151 * _tmp210 + _tmp152 * _tmp91 + _tmp153 * _tmp93;
    _P_updated(4, 10) = P(4, 10) - P(6, 10) * _tmp154 - P(7, 10) * _tmp155 - P(8, 10) * _tmp156 +
                        _tmp157 * _tmp91 + _tmp158 * _tmp92 - _tmp159 * _tmp209 -
                        _tmp160 * _tmp208 - _tmp161 * _tmp210 + _tmp162 * _tmp93;
    _P_updated(5, 10) = P(5, 10) - P(6, 10) * _tmp165 - P(7, 10) * _tmp164 - P(8, 10) * _tmp166 +
                        _tmp163 * _tmp91 + _tmp167 * _tmp93 - _tmp168 * _tmp210 -
                        _tmp169 * _tmp209 - _tmp170 * _tmp208 + _tmp171 * _tmp92;
    _P_updated(6, 10) = P(6, 10) * _tmp175 - P(7, 10) * _tmp173 - P(8, 10) * _tmp174 +
                        _tmp172 * _tmp91 - _tmp176 * _tmp208 - _tmp177 * _tmp209 -
                        _tmp178 * _tmp210 + _tmp179 * _tmp93 + _tmp180 * _tmp92;
    _P_updated(7, 10) = -P(6, 10) * _tmp181 + P(7, 10) * _tmp183 - P(8, 10) * _tmp182 -
                        _tmp184 * _tmp208 - _tmp185 * _tmp210 - _tmp186 * _tmp209 +
                        _tmp187 * _tmp92 + _tmp188 * _tmp91 + _tmp189 * _tmp93;
    _P_updated(8, 10) = -P(6, 10) * _tmp192 - P(7, 10) * _tmp191 + P(8, 10) * _tmp193 +
                        _tmp190 * _tmp91 - _tmp194 * _tmp208 - _tmp195 * _tmp210 -
                        _tmp196 * _tmp209 + _tmp197 * _tmp92 + _tmp198 * _tmp93;
    _P_updated(9, 10) = -P(6, 10) * _tmp201 - P(7, 10) * _tmp200 - P(8, 10) * _tmp199 + P(9, 10) +
                        _tmp202 * _tmp91 + _tmp203 * _tmp92 + _tmp204 * _tmp93 - _tmp205 * _tmp208 -
                        _tmp206 * _tmp210 - _tmp207 * _tmp209;
    _P_updated(10, 10) = P(10, 10) - P(6, 10) * _tmp208 - P(7, 10) * _tmp209 - P(8, 10) * _tmp210 -
                         _tmp208 * _tmp212 - _tmp209 * _tmp211 - _tmp210 * _tmp213 +
                         _tmp214 * _tmp92 + _tmp215 * _tmp91 + _tmp216 * _tmp93;
    _P_updated(11, 10) = P(11, 10) - P(6, 10) * _tmp219 - P(7, 10) * _tmp217 - P(8, 10) * _tmp218 -
                         _tmp208 * _tmp223 - _tmp209 * _tmp224 - _tmp210 * _tmp225 +
                         _tmp220 * _tmp91 + _tmp221 * _tmp93 + _tmp222 * _tmp92;
    _P_updated(12, 10) = P(12, 10) - P(6, 10) * _tmp226 - P(7, 10) * _tmp227 - P(8, 10) * _tmp228 -
                         _tmp208 * _tmp231 - _tmp209 * _tmp229 - _tmp210 * _tmp230 +
                         _tmp232 * _tmp92 + _tmp233 * _tmp91 + _tmp234 * _tmp93;
    _P_updated(13, 10) = P(13, 10) - P(6, 10) * _tmp235 - P(7, 10) * _tmp236 - P(8, 10) * _tmp237 -
                         _tmp208 * _tmp242 - _tmp209 * _tmp240 - _tmp210 * _tmp241 +
                         _tmp238 * _tmp93 + _tmp239 * _tmp91 + _tmp243 * _tmp92;
    _P_updated(14, 10) = P(14, 10) - P(6, 10) * _tmp245 - P(7, 10) * _tmp247 - P(8, 10) * _tmp246 -
                         _tmp208 * _tmp250 - _tmp209 * _tmp249 - _tmp210 * _tmp248 +
                         _tmp244 * _tmp93 + _tmp251 * _tmp91 + _tmp252 * _tmp92;
    _P_updated(0, 11) = P(0, 11) - P(6, 11) * _tmp121 - P(7, 11) * _tmp122 - P(8, 11) * _tmp123 +
                        _tmp118 * _tmp99 + _tmp119 * _tmp97 + _tmp120 * _tmp98 - _tmp124 * _tmp217 -
                        _tmp125 * _tmp218 - _tmp126 * _tmp219;
    _P_updated(1, 11) = P(1, 11) - P(6, 11) * _tmp132 - P(7, 11) * _tmp131 - P(8, 11) * _tmp130 +
                        _tmp127 * _tmp98 + _tmp128 * _tmp97 + _tmp129 * _tmp99 - _tmp133 * _tmp218 -
                        _tmp134 * _tmp217 - _tmp135 * _tmp219;
    _P_updated(2, 11) = P(2, 11) - P(6, 11) * _tmp138 - P(7, 11) * _tmp136 - P(8, 11) * _tmp137 +
                        _tmp139 * _tmp99 - _tmp140 * _tmp217 - _tmp141 * _tmp218 -
                        _tmp142 * _tmp219 + _tmp143 * _tmp97 + _tmp144 * _tmp98;
    _P_updated(3, 11) = P(3, 11) - P(6, 11) * _tmp146 - P(7, 11) * _tmp147 - P(8, 11) * _tmp148 +
                        _tmp145 * _tmp99 - _tmp149 * _tmp219 - _tmp150 * _tmp217 -
                        _tmp151 * _tmp218 + _tmp152 * _tmp98 + _tmp153 * _tmp97;
    _P_updated(4, 11) = P(4, 11) - P(6, 11) * _tmp154 - P(7, 11) * _tmp155 - P(8, 11) * _tmp156 +
                        _tmp157 * _tmp98 + _tmp158 * _tmp99 - _tmp159 * _tmp217 -
                        _tmp160 * _tmp219 - _tmp161 * _tmp218 + _tmp162 * _tmp97;
    _P_updated(5, 11) = P(5, 11) - P(6, 11) * _tmp165 - P(7, 11) * _tmp164 - P(8, 11) * _tmp166 +
                        _tmp163 * _tmp98 + _tmp167 * _tmp97 - _tmp168 * _tmp218 -
                        _tmp169 * _tmp217 - _tmp170 * _tmp219 + _tmp171 * _tmp99;
    _P_updated(6, 11) = P(6, 11) * _tmp175 - P(7, 11) * _tmp173 - P(8, 11) * _tmp174 +
                        _tmp172 * _tmp98 - _tmp176 * _tmp219 - _tmp177 * _tmp217 -
                        _tmp178 * _tmp218 + _tmp179 * _tmp97 + _tmp180 * _tmp99;
    _P_updated(7, 11) = -P(6, 11) * _tmp181 + P(7, 11) * _tmp183 - P(8, 11) * _tmp182 -
                        _tmp184 * _tmp219 - _tmp185 * _tmp218 - _tmp186 * _tmp217 +
                        _tmp187 * _tmp99 + _tmp188 * _tmp98 + _tmp189 * _tmp97;
    _P_updated(8, 11) = -P(6, 11) * _tmp192 - P(7, 11) * _tmp191 + P(8, 11) * _tmp193 +
                        _tmp190 * _tmp98 - _tmp194 * _tmp219 - _tmp195 * _tmp218 -
                        _tmp196 * _tmp217 + _tmp197 * _tmp99 + _tmp198 * _tmp97;
    _P_updated(9, 11) = -P(6, 11) * _tmp201 - P(7, 11) * _tmp200 - P(8, 11) * _tmp199 + P(9, 11) +
                        _tmp202 * _tmp98 + _tmp203 * _tmp99 + _tmp204 * _tmp97 - _tmp205 * _tmp219 -
                        _tmp206 * _tmp218 - _tmp207 * _tmp217;
    _P_updated(10, 11) = P(10, 11) - P(6, 11) * _tmp208 - P(7, 11) * _tmp209 - P(8, 11) * _tmp210 -
                         _tmp211 * _tmp217 - _tmp212 * _tmp219 - _tmp213 * _tmp218 +
                         _tmp214 * _tmp99 + _tmp215 * _tmp98 + _tmp216 * _tmp97;
    _P_updated(11, 11) = P(11, 11) - P(6, 11) * _tmp219 - P(7, 11) * _tmp217 - P(8, 11) * _tmp218 -
                         _tmp217 * _tmp224 - _tmp218 * _tmp225 - _tmp219 * _tmp223 +
                         _tmp220 * _tmp98 + _tmp221 * _tmp97 + _tmp222 * _tmp99;
    _P_updated(12, 11) = P(12, 11) - P(6, 11) * _tmp226 - P(7, 11) * _tmp227 - P(8, 11) * _tmp228 -
                         _tmp217 * _tmp229 - _tmp218 * _tmp230 - _tmp219 * _tmp231 +
                         _tmp232 * _tmp99 + _tmp233 * _tmp98 + _tmp234 * _tmp97;
    _P_updated(13, 11) = P(13, 11) - P(6, 11) * _tmp235 - P(7, 11) * _tmp236 - P(8, 11) * _tmp237 -
                         _tmp217 * _tmp240 - _tmp218 * _tmp241 - _tmp219 * _tmp242 +
                         _tmp238 * _tmp97 + _tmp239 * _tmp98 + _tmp243 * _tmp99;
    _P_updated(14, 11) = P(14, 11) - P(6, 11) * _tmp245 - P(7, 11) * _tmp247 - P(8, 11) * _tmp246 -
                         _tmp217 * _tmp249 - _tmp218 * _tmp248 - _tmp219 * _tmp250 +
                         _tmp244 * _tmp97 + _tmp251 * _tmp98 + _tmp252 * _tmp99;
    _P_updated(0, 12) = P(0, 12) - P(6, 12) * _tmp121 - P(7, 12) * _tmp122 - P(8, 12) * _tmp123 +
                        _tmp103 * _tmp119 + _tmp104 * _tmp118 + _tmp105 * _tmp120 -
                        _tmp124 * _tmp227 - _tmp125 * _tmp228 - _tmp126 * _tmp226;
    _P_updated(1, 12) = P(1, 12) - P(6, 12) * _tmp132 - P(7, 12) * _tmp131 - P(8, 12) * _tmp130 +
                        _tmp103 * _tmp128 + _tmp104 * _tmp129 + _tmp105 * _tmp127 -
                        _tmp133 * _tmp228 - _tmp134 * _tmp227 - _tmp135 * _tmp226;
    _P_updated(2, 12) = P(2, 12) - P(6, 12) * _tmp138 - P(7, 12) * _tmp136 - P(8, 12) * _tmp137 +
                        _tmp103 * _tmp143 + _tmp104 * _tmp139 + _tmp105 * _tmp144 -
                        _tmp140 * _tmp227 - _tmp141 * _tmp228 - _tmp142 * _tmp226;
    _P_updated(3, 12) = P(3, 12) - P(6, 12) * _tmp146 - P(7, 12) * _tmp147 - P(8, 12) * _tmp148 +
                        _tmp103 * _tmp153 + _tmp104 * _tmp145 + _tmp105 * _tmp152 -
                        _tmp149 * _tmp226 - _tmp150 * _tmp227 - _tmp151 * _tmp228;
    _P_updated(4, 12) = P(4, 12) - P(6, 12) * _tmp154 - P(7, 12) * _tmp155 - P(8, 12) * _tmp156 +
                        _tmp103 * _tmp162 + _tmp104 * _tmp158 + _tmp105 * _tmp157 -
                        _tmp159 * _tmp227 - _tmp160 * _tmp226 - _tmp161 * _tmp228;
    _P_updated(5, 12) = P(5, 12) - P(6, 12) * _tmp165 - P(7, 12) * _tmp164 - P(8, 12) * _tmp166 +
                        _tmp103 * _tmp167 + _tmp104 * _tmp171 + _tmp105 * _tmp163 -
                        _tmp168 * _tmp228 - _tmp169 * _tmp227 - _tmp170 * _tmp226;
    _P_updated(6, 12) = P(6, 12) * _tmp175 - P(7, 12) * _tmp173 - P(8, 12) * _tmp174 +
                        _tmp103 * _tmp179 + _tmp104 * _tmp180 + _tmp105 * _tmp172 -
                        _tmp176 * _tmp226 - _tmp177 * _tmp227 - _tmp178 * _tmp228;
    _P_updated(7, 12) = -P(6, 12) * _tmp181 + P(7, 12) * _tmp183 - P(8, 12) * _tmp182 +
                        _tmp103 * _tmp189 + _tmp104 * _tmp187 + _tmp105 * _tmp188 -
                        _tmp184 * _tmp226 - _tmp185 * _tmp228 - _tmp186 * _tmp227;
    _P_updated(8, 12) = -P(6, 12) * _tmp192 - P(7, 12) * _tmp191 + P(8, 12) * _tmp193 +
                        _tmp103 * _tmp198 + _tmp104 * _tmp197 + _tmp105 * _tmp190 -
                        _tmp194 * _tmp226 - _tmp195 * _tmp228 - _tmp196 * _tmp227;
    _P_updated(9, 12) = -P(6, 12) * _tmp201 - P(7, 12) * _tmp200 - P(8, 12) * _tmp199 + P(9, 12) +
                        _tmp103 * _tmp204 + _tmp104 * _tmp203 + _tmp105 * _tmp202 -
                        _tmp205 * _tmp226 - _tmp206 * _tmp228 - _tmp207 * _tmp227;
    _P_updated(10, 12) = P(10, 12) - P(6, 12) * _tmp208 - P(7, 12) * _tmp209 - P(8, 12) * _tmp210 +
                         _tmp103 * _tmp216 + _tmp104 * _tmp214 + _tmp105 * _tmp215 -
                         _tmp211 * _tmp227 - _tmp212 * _tmp226 - _tmp213 * _tmp228;
    _P_updated(11, 12) = P(11, 12) - P(6, 12) * _tmp219 - P(7, 12) * _tmp217 - P(8, 12) * _tmp218 +
                         _tmp103 * _tmp221 + _tmp104 * _tmp222 + _tmp105 * _tmp220 -
                         _tmp223 * _tmp226 - _tmp224 * _tmp227 - _tmp225 * _tmp228;
    _P_updated(12, 12) = P(12, 12) - P(6, 12) * _tmp226 - P(7, 12) * _tmp227 - P(8, 12) * _tmp228 +
                         _tmp103 * _tmp234 + _tmp104 * _tmp232 + _tmp105 * _tmp233 -
                         _tmp226 * _tmp231 - _tmp227 * _tmp229 - _tmp228 * _tmp230;
    _P_updated(13, 12) = P(13, 12) - P(6, 12) * _tmp235 - P(7, 12) * _tmp236 - P(8, 12) * _tmp237 +
                         _tmp103 * _tmp238 + _tmp104 * _tmp243 + _tmp105 * _tmp239 -
                         _tmp226 * _tmp242 - _tmp227 * _tmp240 - _tmp228 * _tmp241;
    _P_updated(14, 12) = P(14, 12) - P(6, 12) * _tmp245 - P(7, 12) * _tmp247 - P(8, 12) * _tmp246 +
                         _tmp103 * _tmp244 + _tmp104 * _tmp252 + _tmp105 * _tmp251 -
                         _tmp226 * _tmp250 - _tmp227 * _tmp249 - _tmp228 * _tmp248;
    _P_updated(0, 13) = P(0, 13) - P(6, 13) * _tmp121 - P(7, 13) * _tmp122 - P(8, 13) * _tmp123 +
                        _tmp109 * _tmp118 + _tmp110 * _tmp120 + _tmp111 * _tmp119 -
                        _tmp124 * _tmp236 - _tmp125 * _tmp237 - _tmp126 * _tmp235;
    _P_updated(1, 13) = P(1, 13) - P(6, 13) * _tmp132 - P(7, 13) * _tmp131 - P(8, 13) * _tmp130 +
                        _tmp109 * _tmp129 + _tmp110 * _tmp127 + _tmp111 * _tmp128 -
                        _tmp133 * _tmp237 - _tmp134 * _tmp236 - _tmp135 * _tmp235;
    _P_updated(2, 13) = P(2, 13) - P(6, 13) * _tmp138 - P(7, 13) * _tmp136 - P(8, 13) * _tmp137 +
                        _tmp109 * _tmp139 + _tmp110 * _tmp144 + _tmp111 * _tmp143 -
                        _tmp140 * _tmp236 - _tmp141 * _tmp237 - _tmp142 * _tmp235;
    _P_updated(3, 13) = P(3, 13) - P(6, 13) * _tmp146 - P(7, 13) * _tmp147 - P(8, 13) * _tmp148 +
                        _tmp109 * _tmp145 + _tmp110 * _tmp152 + _tmp111 * _tmp153 -
                        _tmp149 * _tmp235 - _tmp150 * _tmp236 - _tmp151 * _tmp237;
    _P_updated(4, 13) = P(4, 13) - P(6, 13) * _tmp154 - P(7, 13) * _tmp155 - P(8, 13) * _tmp156 +
                        _tmp109 * _tmp158 + _tmp110 * _tmp157 + _tmp111 * _tmp162 -
                        _tmp159 * _tmp236 - _tmp160 * _tmp235 - _tmp161 * _tmp237;
    _P_updated(5, 13) = P(5, 13) - P(6, 13) * _tmp165 - P(7, 13) * _tmp164 - P(8, 13) * _tmp166 +
                        _tmp109 * _tmp171 + _tmp110 * _tmp163 + _tmp111 * _tmp167 -
                        _tmp168 * _tmp237 - _tmp169 * _tmp236 - _tmp170 * _tmp235;
    _P_updated(6, 13) = P(6, 13) * _tmp175 - P(7, 13) * _tmp173 - P(8, 13) * _tmp174 +
                        _tmp109 * _tmp180 + _tmp110 * _tmp172 + _tmp111 * _tmp179 -
                        _tmp176 * _tmp235 - _tmp177 * _tmp236 - _tmp178 * _tmp237;
    _P_updated(7, 13) = -P(6, 13) * _tmp181 + P(7, 13) * _tmp183 - P(8, 13) * _tmp182 +
                        _tmp109 * _tmp187 + _tmp110 * _tmp188 + _tmp111 * _tmp189 -
                        _tmp184 * _tmp235 - _tmp185 * _tmp237 - _tmp186 * _tmp236;
    _P_updated(8, 13) = -P(6, 13) * _tmp192 - P(7, 13) * _tmp191 + P(8, 13) * _tmp193 +
                        _tmp109 * _tmp197 + _tmp110 * _tmp190 + _tmp111 * _tmp198 -
                        _tmp194 * _tmp235 - _tmp195 * _tmp237 - _tmp196 * _tmp236;
    _P_updated(9, 13) = -P(6, 13) * _tmp201 - P(7, 13) * _tmp200 - P(8, 13) * _tmp199 + P(9, 13) +
                        _tmp109 * _tmp203 + _tmp110 * _tmp202 + _tmp111 * _tmp204 -
                        _tmp205 * _tmp235 - _tmp206 * _tmp237 - _tmp207 * _tmp236;
    _P_updated(10, 13) = P(10, 13) - P(6, 13) * _tmp208 - P(7, 13) * _tmp209 - P(8, 13) * _tmp210 +
                         _tmp109 * _tmp214 + _tmp110 * _tmp215 + _tmp111 * _tmp216 -
                         _tmp211 * _tmp236 - _tmp212 * _tmp235 - _tmp213 * _tmp237;
    _P_updated(11, 13) = P(11, 13) - P(6, 13) * _tmp219 - P(7, 13) * _tmp217 - P(8, 13) * _tmp218 +
                         _tmp109 * _tmp222 + _tmp110 * _tmp220 + _tmp111 * _tmp221 -
                         _tmp223 * _tmp235 - _tmp224 * _tmp236 - _tmp225 * _tmp237;
    _P_updated(12, 13) = P(12, 13) - P(6, 13) * _tmp226 - P(7, 13) * _tmp227 - P(8, 13) * _tmp228 +
                         _tmp109 * _tmp232 + _tmp110 * _tmp233 + _tmp111 * _tmp234 -
                         _tmp229 * _tmp236 - _tmp230 * _tmp237 - _tmp231 * _tmp235;
    _P_updated(13, 13) = P(13, 13) - P(6, 13) * _tmp235 - P(7, 13) * _tmp236 - P(8, 13) * _tmp237 +
                         _tmp109 * _tmp243 + _tmp110 * _tmp239 + _tmp111 * _tmp238 -
                         _tmp235 * _tmp242 - _tmp236 * _tmp240 - _tmp237 * _tmp241;
    _P_updated(14, 13) = P(14, 13) - P(6, 13) * _tmp245 - P(7, 13) * _tmp247 - P(8, 13) * _tmp246 +
                         _tmp109 * _tmp252 + _tmp110 * _tmp251 + _tmp111 * _tmp244 -
                         _tmp235 * _tmp250 - _tmp236 * _tmp249 - _tmp237 * _tmp248;
    _P_updated(0, 14) = P(0, 14) - P(6, 14) * _tmp121 - P(7, 14) * _tmp122 - P(8, 14) * _tmp123 +
                        _tmp115 * _tmp120 + _tmp116 * _tmp119 + _tmp117 * _tmp118 -
                        _tmp124 * _tmp247 - _tmp125 * _tmp246 - _tmp126 * _tmp245;
    _P_updated(1, 14) = P(1, 14) - P(6, 14) * _tmp132 - P(7, 14) * _tmp131 - P(8, 14) * _tmp130 +
                        _tmp115 * _tmp127 + _tmp116 * _tmp128 + _tmp117 * _tmp129 -
                        _tmp133 * _tmp246 - _tmp134 * _tmp247 - _tmp135 * _tmp245;
    _P_updated(2, 14) = P(2, 14) - P(6, 14) * _tmp138 - P(7, 14) * _tmp136 - P(8, 14) * _tmp137 +
                        _tmp115 * _tmp144 + _tmp116 * _tmp143 + _tmp117 * _tmp139 -
                        _tmp140 * _tmp247 - _tmp141 * _tmp246 - _tmp142 * _tmp245;
    _P_updated(3, 14) = P(3, 14) - P(6, 14) * _tmp146 - P(7, 14) * _tmp147 - P(8, 14) * _tmp148 +
                        _tmp115 * _tmp152 + _tmp116 * _tmp153 + _tmp117 * _tmp145 -
                        _tmp149 * _tmp245 - _tmp150 * _tmp247 - _tmp151 * _tmp246;
    _P_updated(4, 14) = P(4, 14) - P(6, 14) * _tmp154 - P(7, 14) * _tmp155 - P(8, 14) * _tmp156 +
                        _tmp115 * _tmp157 + _tmp116 * _tmp162 + _tmp117 * _tmp158 -
                        _tmp159 * _tmp247 - _tmp160 * _tmp245 - _tmp161 * _tmp246;
    _P_updated(5, 14) = P(5, 14) - P(6, 14) * _tmp165 - P(7, 14) * _tmp164 - P(8, 14) * _tmp166 +
                        _tmp115 * _tmp163 + _tmp116 * _tmp167 + _tmp117 * _tmp171 -
                        _tmp168 * _tmp246 - _tmp169 * _tmp247 - _tmp170 * _tmp245;
    _P_updated(6, 14) = P(6, 14) * _tmp175 - P(7, 14) * _tmp173 - P(8, 14) * _tmp174 +
                        _tmp115 * _tmp172 + _tmp116 * _tmp179 + _tmp117 * _tmp180 -
                        _tmp176 * _tmp245 - _tmp177 * _tmp247 - _tmp178 * _tmp246;
    _P_updated(7, 14) = -P(6, 14) * _tmp181 + P(7, 14) * _tmp183 - P(8, 14) * _tmp182 +
                        _tmp115 * _tmp188 + _tmp116 * _tmp189 + _tmp117 * _tmp187 -
                        _tmp184 * _tmp245 - _tmp185 * _tmp246 - _tmp186 * _tmp247;
    _P_updated(8, 14) = -P(6, 14) * _tmp192 - P(7, 14) * _tmp191 + P(8, 14) * _tmp193 +
                        _tmp115 * _tmp190 + _tmp116 * _tmp198 + _tmp117 * _tmp197 -
                        _tmp194 * _tmp245 - _tmp195 * _tmp246 - _tmp196 * _tmp247;
    _P_updated(9, 14) = -P(6, 14) * _tmp201 - P(7, 14) * _tmp200 - P(8, 14) * _tmp199 + P(9, 14) +
                        _tmp115 * _tmp202 + _tmp116 * _tmp204 + _tmp117 * _tmp203 -
                        _tmp205 * _tmp245 - _tmp206 * _tmp246 - _tmp207 * _tmp247;
    _P_updated(10, 14) = P(10, 14) - P(6, 14) * _tmp208 - P(7, 14) * _tmp209 - P(8, 14) * _tmp210 +
                         _tmp115 * _tmp215 + _tmp116 * _tmp216 + _tmp117 * _tmp214 -
                         _tmp211 * _tmp247 - _tmp212 * _tmp245 - _tmp213 * _tmp246;
    _P_updated(11, 14) = P(11, 14) - P(6, 14) * _tmp219 - P(7, 14) * _tmp217 - P(8, 14) * _tmp218 +
                         _tmp115 * _tmp220 + _tmp116 * _tmp221 + _tmp117 * _tmp222 -
                         _tmp223 * _tmp245 - _tmp224 * _tmp247 - _tmp225 * _tmp246;
    _P_updated(12, 14) = P(12, 14) - P(6, 14) * _tmp226 - P(7, 14) * _tmp227 - P(8, 14) * _tmp228 +
                         _tmp115 * _tmp233 + _tmp116 * _tmp234 + _tmp117 * _tmp232 -
                         _tmp229 * _tmp247 - _tmp230 * _tmp246 - _tmp231 * _tmp245;
    _P_updated(13, 14) = P(13, 14) - P(6, 14) * _tmp235 - P(7, 14) * _tmp236 - P(8, 14) * _tmp237 +
                         _tmp115 * _tmp239 + _tmp116 * _tmp238 + _tmp117 * _tmp243 -
                         _tmp240 * _tmp247 - _tmp241 * _tmp246 - _tmp242 * _tmp245;
    _P_updated(14, 14) = P(14, 14) - P(6, 14) * _tmp245 - P(7, 14) * _tmp247 - P(8, 14) * _tmp246 +
                         _tmp115 * _tmp251 + _tmp116 * _tmp244 + _tmp117 * _tmp252 -
                         _tmp245 * _tmp250 - _tmp246 * _tmp248 - _tmp247 * _tmp249;
  }

  if (innov_cov != nullptr) {
    Eigen::Matrix<Scalar, 3, 3>& _innov_cov = (*innov_cov);

    _innov_cov(0, 0) = _tmp8;
    _innov_cov(1, 0) = _tmp10;
    _innov_cov(2, 0) = _tmp18;
    _innov_cov(0, 1) = _tmp4;
    _innov_cov(1, 1) = _tmp12;
    _innov_cov(2, 1) = _tmp22;
    _innov_cov(0, 2) = _tmp17;
    _innov_cov(1, 2) = _tmp20;
    _innov_cov(2, 2) = _tmp24;
  }
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace gnc
