// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <ArduinoEigen/Eigen/Core>

#include "sym_minimal.h"

namespace gnc {

/**
 * This function was autogenerated. Do not modify by hand.
 *
 * Args:
 *     pos: Matrix31
 *     vel: Matrix31
 *     quat: Rot3
 *     ab: Matrix31
 *     gb: Matrix31
 *     P: Matrix15_15
 *     delta_vel: Matrix31
 *     delta_ang: Matrix31
 *     delta_vel_dt: Scalar
 *     delta_angle_dt: Scalar
 *     accel_noise_var: Scalar
 *     gyro_noise_var: Scalar
 *     accel_walk_var: Scalar
 *     gyro_walk_var: Scalar
 *     epsilon: Scalar
 *
 * Outputs:
 *     pred_pos: Matrix31
 *     pred_vel: Matrix31
 *     pred_quat: Rot3
 *     pred_ab: Matrix31
 *     pred_gb: Matrix31
 *     P_pred: Matrix15_15
 */
template <typename Scalar>
void PredictStates(const Eigen::Matrix<Scalar, 3, 1>& pos, const Eigen::Matrix<Scalar, 3, 1>& vel,
                   const sym::Rot3<Scalar>& quat, const Eigen::Matrix<Scalar, 3, 1>& ab,
                   const Eigen::Matrix<Scalar, 3, 1>& gb, const Eigen::Matrix<Scalar, 15, 15>& P,
                   const Eigen::Matrix<Scalar, 3, 1>& delta_vel,
                   const Eigen::Matrix<Scalar, 3, 1>& delta_ang, const Scalar delta_vel_dt,
                   const Scalar delta_angle_dt, const Scalar accel_noise_var,
                   const Scalar gyro_noise_var, const Scalar accel_walk_var,
                   const Scalar gyro_walk_var, const Scalar epsilon,
                   Eigen::Matrix<Scalar, 3, 1>* const pred_pos = nullptr,
                   Eigen::Matrix<Scalar, 3, 1>* const pred_vel = nullptr,
                   sym::Rot3<Scalar>* const pred_quat = nullptr,
                   Eigen::Matrix<Scalar, 3, 1>* const pred_ab = nullptr,
                   Eigen::Matrix<Scalar, 3, 1>* const pred_gb = nullptr,
                   Eigen::Matrix<Scalar, 15, 15>* const P_pred = nullptr) {
  // Total ops: 2094

  // Input arrays
  const Eigen::Matrix<Scalar, 4, 1>& _quat = quat.Data();

  // Intermediate terms (226)
  const Scalar _tmp0 = 2 * _quat[2];
  const Scalar _tmp1 = _quat[0] * _tmp0;
  const Scalar _tmp2 = 2 * _quat[1];
  const Scalar _tmp3 = _quat[3] * _tmp2;
  const Scalar _tmp4 = _tmp1 + _tmp3;
  const Scalar _tmp5 = -ab(2, 0) * delta_vel_dt + delta_vel(2, 0);
  const Scalar _tmp6 = _quat[3] * _tmp0;
  const Scalar _tmp7 = _quat[0] * _tmp2;
  const Scalar _tmp8 = -_tmp6 + _tmp7;
  const Scalar _tmp9 = -ab(1, 0) * delta_vel_dt + delta_vel(1, 0);
  const Scalar _tmp10 = -2 * std::pow(_quat[2], Scalar(2));
  const Scalar _tmp11 = 1 - 2 * std::pow(_quat[1], Scalar(2));
  const Scalar _tmp12 = _tmp10 + _tmp11;
  const Scalar _tmp13 = -ab(0, 0) * delta_vel_dt + delta_vel(0, 0);
  const Scalar _tmp14 = _tmp12 * _tmp13 + _tmp4 * _tmp5 + _tmp8 * _tmp9;
  const Scalar _tmp15 = Scalar(0.5) * delta_vel_dt;
  const Scalar _tmp16 = 2 * _quat[0] * _quat[3];
  const Scalar _tmp17 = _quat[2] * _tmp2;
  const Scalar _tmp18 = -_tmp16 + _tmp17;
  const Scalar _tmp19 = -2 * std::pow(_quat[0], Scalar(2));
  const Scalar _tmp20 = _tmp10 + _tmp19 + 1;
  const Scalar _tmp21 = _tmp6 + _tmp7;
  const Scalar _tmp22 = _tmp13 * _tmp21 + _tmp18 * _tmp5 + _tmp20 * _tmp9;
  const Scalar _tmp23 = _tmp16 + _tmp17;
  const Scalar _tmp24 = _tmp11 + _tmp19;
  const Scalar _tmp25 = _tmp1 - _tmp3;
  const Scalar _tmp26 =
      _tmp13 * _tmp25 + _tmp23 * _tmp9 + _tmp24 * _tmp5 + Scalar(9.8100000000000005) * delta_vel_dt;
  const Scalar _tmp27 = delta_ang(0, 0) - delta_angle_dt * gb(0, 0);
  const Scalar _tmp28 = std::pow(_tmp27, Scalar(2));
  const Scalar _tmp29 = delta_ang(2, 0) - delta_angle_dt * gb(2, 0);
  const Scalar _tmp30 = std::pow(_tmp29, Scalar(2));
  const Scalar _tmp31 = delta_ang(1, 0) - delta_angle_dt * gb(1, 0);
  const Scalar _tmp32 = std::pow(_tmp31, Scalar(2));
  const Scalar _tmp33 = _tmp28 + _tmp30 + _tmp32 + std::pow(epsilon, Scalar(2));
  const Scalar _tmp34 = std::sqrt(_tmp33);
  const Scalar _tmp35 = (Scalar(1) / Scalar(2)) * _tmp34;
  const Scalar _tmp36 = std::cos(_tmp35);
  const Scalar _tmp37 = std::sin(_tmp35);
  const Scalar _tmp38 = _tmp37 / _tmp34;
  const Scalar _tmp39 = _tmp29 * _tmp38;
  const Scalar _tmp40 = _tmp31 * _tmp38;
  const Scalar _tmp41 = _tmp27 * _tmp38;
  const Scalar _tmp42 = _quat[0] * _tmp38;
  const Scalar _tmp43 = P(0, 3) + P(3, 3) * delta_vel_dt;
  const Scalar _tmp44 = P(1, 3) + P(4, 3) * delta_vel_dt;
  const Scalar _tmp45 = P(2, 3) + P(5, 3) * delta_vel_dt;
  const Scalar _tmp46 = P(9, 3) * delta_vel_dt;
  const Scalar _tmp47 = _tmp12 * _tmp5 - _tmp13 * _tmp4;
  const Scalar _tmp48 = -_tmp12 * _tmp9 + _tmp13 * _tmp8;
  const Scalar _tmp49 = P(10, 3) * delta_vel_dt;
  const Scalar _tmp50 = P(11, 3) * delta_vel_dt;
  const Scalar _tmp51 = _tmp4 * _tmp9 - _tmp5 * _tmp8;
  const Scalar _tmp52 = P(3, 3) + P(6, 3) * _tmp51 + P(7, 3) * _tmp47 + P(8, 3) * _tmp48 -
                        _tmp12 * _tmp46 - _tmp4 * _tmp50 - _tmp49 * _tmp8;
  const Scalar _tmp53 = _tmp12 * delta_vel_dt;
  const Scalar _tmp54 = _tmp8 * delta_vel_dt;
  const Scalar _tmp55 = _tmp4 * delta_vel_dt;
  const Scalar _tmp56 = -_tmp13 * _tmp18 + _tmp21 * _tmp5;
  const Scalar _tmp57 = _tmp18 * _tmp9 - _tmp20 * _tmp5;
  const Scalar _tmp58 = _tmp13 * _tmp20 - _tmp21 * _tmp9;
  const Scalar _tmp59 = P(4, 3) + P(6, 3) * _tmp57 + P(7, 3) * _tmp56 + P(8, 3) * _tmp58 -
                        _tmp18 * _tmp50 - _tmp20 * _tmp49 - _tmp21 * _tmp46;
  const Scalar _tmp60 = _tmp21 * delta_vel_dt;
  const Scalar _tmp61 = _tmp18 * delta_vel_dt;
  const Scalar _tmp62 = _tmp20 * delta_vel_dt;
  const Scalar _tmp63 = -_tmp23 * _tmp5 + _tmp24 * _tmp9;
  const Scalar _tmp64 = _tmp13 * _tmp23 - _tmp25 * _tmp9;
  const Scalar _tmp65 = -_tmp13 * _tmp24 + _tmp25 * _tmp5;
  const Scalar _tmp66 = P(5, 3) + P(6, 3) * _tmp63 + P(7, 3) * _tmp65 + P(8, 3) * _tmp64 -
                        _tmp23 * _tmp49 - _tmp24 * _tmp50 - _tmp25 * _tmp46;
  const Scalar _tmp67 = _tmp25 * delta_vel_dt;
  const Scalar _tmp68 = _tmp23 * delta_vel_dt;
  const Scalar _tmp69 = _tmp24 * delta_vel_dt;
  const Scalar _tmp70 = 2 * _tmp36;
  const Scalar _tmp71 = _tmp40 * _tmp70;
  const Scalar _tmp72 = 2 * std::pow(_tmp37, Scalar(2)) / _tmp33;
  const Scalar _tmp73 = _tmp29 * _tmp72;
  const Scalar _tmp74 = _tmp27 * _tmp73;
  const Scalar _tmp75 = -_tmp71 + _tmp74;
  const Scalar _tmp76 = -_tmp32 * _tmp72;
  const Scalar _tmp77 = -_tmp30 * _tmp72 + 1;
  const Scalar _tmp78 = _tmp76 + _tmp77;
  const Scalar _tmp79 = _tmp27 * _tmp31 * _tmp72;
  const Scalar _tmp80 = _tmp39 * _tmp70;
  const Scalar _tmp81 = _tmp79 + _tmp80;
  const Scalar _tmp82 =
      -P(12, 3) * delta_angle_dt + P(6, 3) * _tmp78 + P(7, 3) * _tmp81 + P(8, 3) * _tmp75;
  const Scalar _tmp83 = _tmp79 - _tmp80;
  const Scalar _tmp84 = _tmp31 * _tmp73;
  const Scalar _tmp85 = _tmp41 * _tmp70;
  const Scalar _tmp86 = _tmp84 + _tmp85;
  const Scalar _tmp87 = -_tmp28 * _tmp72;
  const Scalar _tmp88 = _tmp77 + _tmp87;
  const Scalar _tmp89 =
      -P(13, 3) * delta_angle_dt + P(6, 3) * _tmp83 + P(7, 3) * _tmp88 + P(8, 3) * _tmp86;
  const Scalar _tmp90 = _tmp76 + _tmp87 + 1;
  const Scalar _tmp91 = _tmp71 + _tmp74;
  const Scalar _tmp92 = _tmp84 - _tmp85;
  const Scalar _tmp93 =
      -P(14, 3) * delta_angle_dt + P(6, 3) * _tmp91 + P(7, 3) * _tmp92 + P(8, 3) * _tmp90;
  const Scalar _tmp94 = P(0, 4) + P(3, 4) * delta_vel_dt;
  const Scalar _tmp95 = P(1, 4) + P(4, 4) * delta_vel_dt;
  const Scalar _tmp96 = P(2, 4) + P(5, 4) * delta_vel_dt;
  const Scalar _tmp97 = P(9, 4) * delta_vel_dt;
  const Scalar _tmp98 = P(10, 4) * delta_vel_dt;
  const Scalar _tmp99 = P(11, 4) * delta_vel_dt;
  const Scalar _tmp100 = P(3, 4) + P(6, 4) * _tmp51 + P(7, 4) * _tmp47 + P(8, 4) * _tmp48 -
                         _tmp12 * _tmp97 - _tmp4 * _tmp99 - _tmp8 * _tmp98;
  const Scalar _tmp101 = P(4, 4) + P(6, 4) * _tmp57 + P(7, 4) * _tmp56 + P(8, 4) * _tmp58 -
                         _tmp18 * _tmp99 - _tmp20 * _tmp98 - _tmp21 * _tmp97;
  const Scalar _tmp102 = P(5, 4) + P(6, 4) * _tmp63 + P(7, 4) * _tmp65 + P(8, 4) * _tmp64 -
                         _tmp23 * _tmp98 - _tmp24 * _tmp99 - _tmp25 * _tmp97;
  const Scalar _tmp103 =
      -P(12, 4) * delta_angle_dt + P(6, 4) * _tmp78 + P(7, 4) * _tmp81 + P(8, 4) * _tmp75;
  const Scalar _tmp104 =
      -P(13, 4) * delta_angle_dt + P(6, 4) * _tmp83 + P(7, 4) * _tmp88 + P(8, 4) * _tmp86;
  const Scalar _tmp105 =
      -P(14, 4) * delta_angle_dt + P(6, 4) * _tmp91 + P(7, 4) * _tmp92 + P(8, 4) * _tmp90;
  const Scalar _tmp106 = P(0, 5) + P(3, 5) * delta_vel_dt;
  const Scalar _tmp107 = P(1, 5) + P(4, 5) * delta_vel_dt;
  const Scalar _tmp108 = P(2, 5) + P(5, 5) * delta_vel_dt;
  const Scalar _tmp109 = P(9, 5) * delta_vel_dt;
  const Scalar _tmp110 = P(10, 5) * delta_vel_dt;
  const Scalar _tmp111 = P(11, 5) * delta_vel_dt;
  const Scalar _tmp112 = P(3, 5) + P(6, 5) * _tmp51 + P(7, 5) * _tmp47 + P(8, 5) * _tmp48 -
                         _tmp109 * _tmp12 - _tmp110 * _tmp8 - _tmp111 * _tmp4;
  const Scalar _tmp113 = P(4, 5) + P(6, 5) * _tmp57 + P(7, 5) * _tmp56 + P(8, 5) * _tmp58 -
                         _tmp109 * _tmp21 - _tmp110 * _tmp20 - _tmp111 * _tmp18;
  const Scalar _tmp114 = P(5, 5) + P(6, 5) * _tmp63 + P(7, 5) * _tmp65 + P(8, 5) * _tmp64 -
                         _tmp109 * _tmp25 - _tmp110 * _tmp23 - _tmp111 * _tmp24;
  const Scalar _tmp115 =
      -P(12, 5) * delta_angle_dt + P(6, 5) * _tmp78 + P(7, 5) * _tmp81 + P(8, 5) * _tmp75;
  const Scalar _tmp116 =
      -P(13, 5) * delta_angle_dt + P(6, 5) * _tmp83 + P(7, 5) * _tmp88 + P(8, 5) * _tmp86;
  const Scalar _tmp117 =
      -P(14, 5) * delta_angle_dt + P(6, 5) * _tmp91 + P(7, 5) * _tmp92 + P(8, 5) * _tmp90;
  const Scalar _tmp118 = P(0, 6) + P(3, 6) * delta_vel_dt;
  const Scalar _tmp119 = P(0, 8) + P(3, 8) * delta_vel_dt;
  const Scalar _tmp120 = P(0, 11) + P(3, 11) * delta_vel_dt;
  const Scalar _tmp121 = P(0, 10) + P(3, 10) * delta_vel_dt;
  const Scalar _tmp122 = P(0, 9) + P(3, 9) * delta_vel_dt;
  const Scalar _tmp123 = P(0, 7) + P(3, 7) * delta_vel_dt;
  const Scalar _tmp124 = P(1, 6) + P(4, 6) * delta_vel_dt;
  const Scalar _tmp125 = P(1, 8) + P(4, 8) * delta_vel_dt;
  const Scalar _tmp126 = P(1, 11) + P(4, 11) * delta_vel_dt;
  const Scalar _tmp127 = P(1, 10) + P(4, 10) * delta_vel_dt;
  const Scalar _tmp128 = P(1, 7) + P(4, 7) * delta_vel_dt;
  const Scalar _tmp129 = P(1, 9) + P(4, 9) * delta_vel_dt;
  const Scalar _tmp130 = P(2, 6) + P(5, 6) * delta_vel_dt;
  const Scalar _tmp131 = P(2, 8) + P(5, 8) * delta_vel_dt;
  const Scalar _tmp132 = P(2, 7) + P(5, 7) * delta_vel_dt;
  const Scalar _tmp133 = P(2, 10) + P(5, 10) * delta_vel_dt;
  const Scalar _tmp134 = P(2, 11) + P(5, 11) * delta_vel_dt;
  const Scalar _tmp135 = P(2, 9) + P(5, 9) * delta_vel_dt;
  const Scalar _tmp136 = accel_noise_var * std::pow(delta_vel_dt, Scalar(2));
  const Scalar _tmp137 = -P(9, 9) * _tmp53;
  const Scalar _tmp138 = -P(10, 9) * _tmp54 - P(11, 9) * _tmp55 + P(3, 9) + P(6, 9) * _tmp51 +
                         P(7, 9) * _tmp47 + P(8, 9) * _tmp48 + _tmp137;
  const Scalar _tmp139 = -P(10, 6) * _tmp54 - P(11, 6) * _tmp55 + P(3, 6) + P(6, 6) * _tmp51 +
                         P(7, 6) * _tmp47 + P(8, 6) * _tmp48 - P(9, 6) * _tmp53;
  const Scalar _tmp140 = -P(10, 8) * _tmp54 - P(11, 8) * _tmp55 + P(3, 8) + P(6, 8) * _tmp51 +
                         P(7, 8) * _tmp47 + P(8, 8) * _tmp48 - P(9, 8) * _tmp53;
  const Scalar _tmp141 = -P(10, 7) * _tmp54 - P(11, 7) * _tmp55 + P(3, 7) + P(6, 7) * _tmp51 +
                         P(7, 7) * _tmp47 + P(8, 7) * _tmp48 - P(9, 7) * _tmp53;
  const Scalar _tmp142 = -P(10, 10) * _tmp54;
  const Scalar _tmp143 = -P(11, 10) * _tmp55 + P(3, 10) + P(6, 10) * _tmp51 + P(7, 10) * _tmp47 +
                         P(8, 10) * _tmp48 - P(9, 10) * _tmp53 + _tmp142;
  const Scalar _tmp144 = -P(11, 11) * _tmp55;
  const Scalar _tmp145 = -P(10, 11) * _tmp54 + P(3, 11) + P(6, 11) * _tmp51 + P(7, 11) * _tmp47 +
                         P(8, 11) * _tmp48 - P(9, 11) * _tmp53 + _tmp144;
  const Scalar _tmp146 = -P(11, 11) * _tmp61;
  const Scalar _tmp147 = -P(10, 11) * _tmp62 + P(4, 11) + P(6, 11) * _tmp57 + P(7, 11) * _tmp56 +
                         P(8, 11) * _tmp58 - P(9, 11) * _tmp60 + _tmp146;
  const Scalar _tmp148 = -P(10, 10) * _tmp62;
  const Scalar _tmp149 = -P(11, 10) * _tmp61 + P(4, 10) + P(6, 10) * _tmp57 + P(7, 10) * _tmp56 +
                         P(8, 10) * _tmp58 - P(9, 10) * _tmp60 + _tmp148;
  const Scalar _tmp150 = -P(9, 9) * _tmp60;
  const Scalar _tmp151 = -P(10, 9) * _tmp62 - P(11, 9) * _tmp61 + P(4, 9) + P(6, 9) * _tmp57 +
                         P(7, 9) * _tmp56 + P(8, 9) * _tmp58 + _tmp150;
  const Scalar _tmp152 = -P(10, 7) * _tmp62 - P(11, 7) * _tmp61 + P(4, 7) + P(6, 7) * _tmp57 +
                         P(7, 7) * _tmp56 + P(8, 7) * _tmp58 - P(9, 7) * _tmp60;
  const Scalar _tmp153 = -P(10, 6) * _tmp62 - P(11, 6) * _tmp61 + P(4, 6) + P(6, 6) * _tmp57 +
                         P(7, 6) * _tmp56 + P(8, 6) * _tmp58 - P(9, 6) * _tmp60;
  const Scalar _tmp154 = -P(10, 8) * _tmp62 - P(11, 8) * _tmp61 + P(4, 8) + P(6, 8) * _tmp57 +
                         P(7, 8) * _tmp56 + P(8, 8) * _tmp58 - P(9, 8) * _tmp60;
  const Scalar _tmp155 = -P(9, 9) * _tmp67;
  const Scalar _tmp156 = -P(10, 9) * _tmp68 - P(11, 9) * _tmp69 + P(5, 9) + P(6, 9) * _tmp63 +
                         P(7, 9) * _tmp65 + P(8, 9) * _tmp64 + _tmp155;
  const Scalar _tmp157 = -P(10, 6) * _tmp68 - P(11, 6) * _tmp69 + P(5, 6) + P(6, 6) * _tmp63 +
                         P(7, 6) * _tmp65 + P(8, 6) * _tmp64 - P(9, 6) * _tmp67;
  const Scalar _tmp158 = -P(11, 11) * _tmp69;
  const Scalar _tmp159 = -P(10, 11) * _tmp68 + P(5, 11) + P(6, 11) * _tmp63 + P(7, 11) * _tmp65 +
                         P(8, 11) * _tmp64 - P(9, 11) * _tmp67 + _tmp158;
  const Scalar _tmp160 = -P(10, 10) * _tmp68;
  const Scalar _tmp161 = -P(11, 10) * _tmp69 + P(5, 10) + P(6, 10) * _tmp63 + P(7, 10) * _tmp65 +
                         P(8, 10) * _tmp64 - P(9, 10) * _tmp67 + _tmp160;
  const Scalar _tmp162 = -P(10, 7) * _tmp68 - P(11, 7) * _tmp69 + P(5, 7) + P(6, 7) * _tmp63 +
                         P(7, 7) * _tmp65 + P(8, 7) * _tmp64 - P(9, 7) * _tmp67;
  const Scalar _tmp163 = -P(10, 8) * _tmp68 - P(11, 8) * _tmp69 + P(5, 8) + P(6, 8) * _tmp63 +
                         P(7, 8) * _tmp65 + P(8, 8) * _tmp64 - P(9, 8) * _tmp67;
  const Scalar _tmp164 =
      -P(12, 7) * delta_angle_dt + P(6, 7) * _tmp78 + P(7, 7) * _tmp81 + P(8, 7) * _tmp75;
  const Scalar _tmp165 =
      -P(12, 8) * delta_angle_dt + P(6, 8) * _tmp78 + P(7, 8) * _tmp81 + P(8, 8) * _tmp75;
  const Scalar _tmp166 =
      -P(12, 10) * delta_angle_dt + P(6, 10) * _tmp78 + P(7, 10) * _tmp81 + P(8, 10) * _tmp75;
  const Scalar _tmp167 =
      -P(12, 11) * delta_angle_dt + P(6, 11) * _tmp78 + P(7, 11) * _tmp81 + P(8, 11) * _tmp75;
  const Scalar _tmp168 =
      -P(12, 6) * delta_angle_dt + P(6, 6) * _tmp78 + P(7, 6) * _tmp81 + P(8, 6) * _tmp75;
  const Scalar _tmp169 =
      -P(12, 9) * delta_angle_dt + P(6, 9) * _tmp78 + P(7, 9) * _tmp81 + P(8, 9) * _tmp75;
  const Scalar _tmp170 = _tmp169 * delta_vel_dt;
  const Scalar _tmp171 =
      -P(13, 7) * delta_angle_dt + P(6, 7) * _tmp83 + P(7, 7) * _tmp88 + P(8, 7) * _tmp86;
  const Scalar _tmp172 =
      -P(13, 9) * delta_angle_dt + P(6, 9) * _tmp83 + P(7, 9) * _tmp88 + P(8, 9) * _tmp86;
  const Scalar _tmp173 =
      -P(13, 8) * delta_angle_dt + P(6, 8) * _tmp83 + P(7, 8) * _tmp88 + P(8, 8) * _tmp86;
  const Scalar _tmp174 =
      -P(13, 6) * delta_angle_dt + P(6, 6) * _tmp83 + P(7, 6) * _tmp88 + P(8, 6) * _tmp86;
  const Scalar _tmp175 =
      -P(13, 11) * delta_angle_dt + P(6, 11) * _tmp83 + P(7, 11) * _tmp88 + P(8, 11) * _tmp86;
  const Scalar _tmp176 =
      -P(13, 10) * delta_angle_dt + P(6, 10) * _tmp83 + P(7, 10) * _tmp88 + P(8, 10) * _tmp86;
  const Scalar _tmp177 =
      -P(14, 9) * delta_angle_dt + P(6, 9) * _tmp91 + P(7, 9) * _tmp92 + P(8, 9) * _tmp90;
  const Scalar _tmp178 =
      -P(14, 6) * delta_angle_dt + P(6, 6) * _tmp91 + P(7, 6) * _tmp92 + P(8, 6) * _tmp90;
  const Scalar _tmp179 =
      -P(14, 10) * delta_angle_dt + P(6, 10) * _tmp91 + P(7, 10) * _tmp92 + P(8, 10) * _tmp90;
  const Scalar _tmp180 =
      -P(14, 11) * delta_angle_dt + P(6, 11) * _tmp91 + P(7, 11) * _tmp92 + P(8, 11) * _tmp90;
  const Scalar _tmp181 =
      -P(14, 7) * delta_angle_dt + P(6, 7) * _tmp91 + P(7, 7) * _tmp92 + P(8, 7) * _tmp90;
  const Scalar _tmp182 =
      -P(14, 8) * delta_angle_dt + P(6, 8) * _tmp91 + P(7, 8) * _tmp92 + P(8, 8) * _tmp90;
  const Scalar _tmp183 = _tmp129 * delta_vel_dt;
  const Scalar _tmp184 = _tmp135 * delta_vel_dt;
  const Scalar _tmp185 = _tmp138 * delta_vel_dt;
  const Scalar _tmp186 = _tmp156 * delta_vel_dt;
  const Scalar _tmp187 = P(0, 12) + P(3, 12) * delta_vel_dt;
  const Scalar _tmp188 = P(1, 12) + P(4, 12) * delta_vel_dt;
  const Scalar _tmp189 = P(2, 12) + P(5, 12) * delta_vel_dt;
  const Scalar _tmp190 = -P(10, 12) * _tmp54 - P(11, 12) * _tmp55 + P(3, 12) + P(6, 12) * _tmp51 +
                         P(7, 12) * _tmp47 + P(8, 12) * _tmp48 - P(9, 12) * _tmp53;
  const Scalar _tmp191 = -P(10, 12) * _tmp62 - P(11, 12) * _tmp61 + P(4, 12) + P(6, 12) * _tmp57 +
                         P(7, 12) * _tmp56 + P(8, 12) * _tmp58 - P(9, 12) * _tmp60;
  const Scalar _tmp192 = -P(10, 12) * _tmp68 - P(11, 12) * _tmp69 + P(5, 12) + P(6, 12) * _tmp63 +
                         P(7, 12) * _tmp65 + P(8, 12) * _tmp64 - P(9, 12) * _tmp67;
  const Scalar _tmp193 = -P(12, 12) * delta_angle_dt;
  const Scalar _tmp194 = P(6, 12) * _tmp78 + P(7, 12) * _tmp81 + P(8, 12) * _tmp75 + _tmp193;
  const Scalar _tmp195 = std::pow(delta_angle_dt, Scalar(2)) * gyro_noise_var;
  const Scalar _tmp196 = -P(13, 12) * delta_angle_dt;
  const Scalar _tmp197 = P(6, 12) * _tmp83 + P(7, 12) * _tmp88 + P(8, 12) * _tmp86 + _tmp196;
  const Scalar _tmp198 = -P(14, 12) * delta_angle_dt;
  const Scalar _tmp199 = P(6, 12) * _tmp91 + P(7, 12) * _tmp92 + P(8, 12) * _tmp90 + _tmp198;
  const Scalar _tmp200 = P(0, 13) + P(3, 13) * delta_vel_dt;
  const Scalar _tmp201 = P(1, 13) + P(4, 13) * delta_vel_dt;
  const Scalar _tmp202 = P(2, 13) + P(5, 13) * delta_vel_dt;
  const Scalar _tmp203 = -P(10, 13) * _tmp54 - P(11, 13) * _tmp55 + P(3, 13) + P(6, 13) * _tmp51 +
                         P(7, 13) * _tmp47 + P(8, 13) * _tmp48 - P(9, 13) * _tmp53;
  const Scalar _tmp204 = -P(10, 13) * _tmp62 - P(11, 13) * _tmp61 + P(4, 13) + P(6, 13) * _tmp57 +
                         P(7, 13) * _tmp56 + P(8, 13) * _tmp58 - P(9, 13) * _tmp60;
  const Scalar _tmp205 = -P(10, 13) * _tmp68 - P(11, 13) * _tmp69 + P(5, 13) + P(6, 13) * _tmp63 +
                         P(7, 13) * _tmp65 + P(8, 13) * _tmp64 - P(9, 13) * _tmp67;
  const Scalar _tmp206 = -P(12, 13) * delta_angle_dt;
  const Scalar _tmp207 = P(6, 13) * _tmp78 + P(7, 13) * _tmp81 + P(8, 13) * _tmp75 + _tmp206;
  const Scalar _tmp208 = -P(13, 13) * delta_angle_dt;
  const Scalar _tmp209 = P(6, 13) * _tmp83 + P(7, 13) * _tmp88 + P(8, 13) * _tmp86 + _tmp208;
  const Scalar _tmp210 = -P(14, 13) * delta_angle_dt;
  const Scalar _tmp211 = P(6, 13) * _tmp91 + P(7, 13) * _tmp92 + P(8, 13) * _tmp90 + _tmp210;
  const Scalar _tmp212 = P(0, 14) + P(3, 14) * delta_vel_dt;
  const Scalar _tmp213 = P(1, 14) + P(4, 14) * delta_vel_dt;
  const Scalar _tmp214 = P(2, 14) + P(5, 14) * delta_vel_dt;
  const Scalar _tmp215 = -P(10, 14) * _tmp54 - P(11, 14) * _tmp55 + P(3, 14) + P(6, 14) * _tmp51 +
                         P(7, 14) * _tmp47 + P(8, 14) * _tmp48 - P(9, 14) * _tmp53;
  const Scalar _tmp216 = -P(10, 14) * _tmp62 - P(11, 14) * _tmp61 + P(4, 14) + P(6, 14) * _tmp57 +
                         P(7, 14) * _tmp56 + P(8, 14) * _tmp58 - P(9, 14) * _tmp60;
  const Scalar _tmp217 = -P(10, 14) * _tmp68 - P(11, 14) * _tmp69 + P(5, 14) + P(6, 14) * _tmp63 +
                         P(7, 14) * _tmp65 + P(8, 14) * _tmp64 - P(9, 14) * _tmp67;
  const Scalar _tmp218 = -P(12, 14) * delta_angle_dt;
  const Scalar _tmp219 = P(6, 14) * _tmp78 + P(7, 14) * _tmp81 + P(8, 14) * _tmp75 + _tmp218;
  const Scalar _tmp220 = -P(13, 14) * delta_angle_dt;
  const Scalar _tmp221 = P(6, 14) * _tmp83 + P(7, 14) * _tmp88 + P(8, 14) * _tmp86 + _tmp220;
  const Scalar _tmp222 = -P(14, 14) * delta_angle_dt;
  const Scalar _tmp223 = P(6, 14) * _tmp91 + P(7, 14) * _tmp92 + P(8, 14) * _tmp90 + _tmp222;
  const Scalar _tmp224 = accel_walk_var * delta_vel_dt;
  const Scalar _tmp225 = delta_angle_dt * gyro_walk_var;

  // Output terms (6)
  if (pred_pos != nullptr) {
    Eigen::Matrix<Scalar, 3, 1>& _pred_pos = (*pred_pos);

    _pred_pos(0, 0) = _tmp14 * _tmp15 + delta_vel_dt * vel(0, 0) + pos(0, 0);
    _pred_pos(1, 0) = _tmp15 * _tmp22 + delta_vel_dt * vel(1, 0) + pos(1, 0);
    _pred_pos(2, 0) = _tmp15 * _tmp26 + delta_vel_dt * vel(2, 0) + pos(2, 0);
  }

  if (pred_vel != nullptr) {
    Eigen::Matrix<Scalar, 3, 1>& _pred_vel = (*pred_vel);

    _pred_vel(0, 0) = _tmp14 + vel(0, 0);
    _pred_vel(1, 0) = _tmp22 + vel(1, 0);
    _pred_vel(2, 0) = _tmp26 + vel(2, 0);
  }

  if (pred_quat != nullptr) {
    Eigen::Matrix<Scalar, 4, 1> _pred_quat;

    _pred_quat[0] = _quat[0] * _tmp36 + _quat[1] * _tmp39 - _quat[2] * _tmp40 + _quat[3] * _tmp41;
    _pred_quat[1] = _quat[1] * _tmp36 + _quat[2] * _tmp41 + _quat[3] * _tmp40 - _tmp29 * _tmp42;
    _pred_quat[2] = -_quat[1] * _tmp41 + _quat[2] * _tmp36 + _quat[3] * _tmp39 + _tmp31 * _tmp42;
    _pred_quat[3] = -_quat[1] * _tmp40 - _quat[2] * _tmp39 + _quat[3] * _tmp36 - _tmp27 * _tmp42;

    *pred_quat = sym::Rot3<Scalar>(_pred_quat);
  }

  if (pred_ab != nullptr) {
    Eigen::Matrix<Scalar, 3, 1>& _pred_ab = (*pred_ab);

    _pred_ab(0, 0) = ab(0, 0);
    _pred_ab(1, 0) = ab(1, 0);
    _pred_ab(2, 0) = ab(2, 0);
  }

  if (pred_gb != nullptr) {
    Eigen::Matrix<Scalar, 3, 1>& _pred_gb = (*pred_gb);

    _pred_gb(0, 0) = gb(0, 0);
    _pred_gb(1, 0) = gb(1, 0);
    _pred_gb(2, 0) = gb(2, 0);
  }

  if (P_pred != nullptr) {
    Eigen::Matrix<Scalar, 15, 15>& _P_pred = (*P_pred);

    _P_pred(0, 0) = P(0, 0) + P(3, 0) * delta_vel_dt + _tmp43 * delta_vel_dt;
    _P_pred(1, 0) = P(1, 0) + P(4, 0) * delta_vel_dt + _tmp44 * delta_vel_dt;
    _P_pred(2, 0) = P(2, 0) + P(5, 0) * delta_vel_dt + _tmp45 * delta_vel_dt;
    _P_pred(3, 0) = -P(10, 0) * _tmp54 - P(11, 0) * _tmp55 + P(3, 0) + P(6, 0) * _tmp51 +
                    P(7, 0) * _tmp47 + P(8, 0) * _tmp48 - P(9, 0) * _tmp53 + _tmp52 * delta_vel_dt;
    _P_pred(4, 0) = -P(10, 0) * _tmp62 - P(11, 0) * _tmp61 + P(4, 0) + P(6, 0) * _tmp57 +
                    P(7, 0) * _tmp56 + P(8, 0) * _tmp58 - P(9, 0) * _tmp60 + _tmp59 * delta_vel_dt;
    _P_pred(5, 0) = -P(10, 0) * _tmp68 - P(11, 0) * _tmp69 + P(5, 0) + P(6, 0) * _tmp63 +
                    P(7, 0) * _tmp65 + P(8, 0) * _tmp64 - P(9, 0) * _tmp67 + _tmp66 * delta_vel_dt;
    _P_pred(6, 0) = -P(12, 0) * delta_angle_dt + P(6, 0) * _tmp78 + P(7, 0) * _tmp81 +
                    P(8, 0) * _tmp75 + _tmp82 * delta_vel_dt;
    _P_pred(7, 0) = -P(13, 0) * delta_angle_dt + P(6, 0) * _tmp83 + P(7, 0) * _tmp88 +
                    P(8, 0) * _tmp86 + _tmp89 * delta_vel_dt;
    _P_pred(8, 0) = -P(14, 0) * delta_angle_dt + P(6, 0) * _tmp91 + P(7, 0) * _tmp92 +
                    P(8, 0) * _tmp90 + _tmp93 * delta_vel_dt;
    _P_pred(9, 0) = P(9, 0) + _tmp46;
    _P_pred(10, 0) = P(10, 0) + _tmp49;
    _P_pred(11, 0) = P(11, 0) + _tmp50;
    _P_pred(12, 0) = P(12, 0) + P(12, 3) * delta_vel_dt;
    _P_pred(13, 0) = P(13, 0) + P(13, 3) * delta_vel_dt;
    _P_pred(14, 0) = P(14, 0) + P(14, 3) * delta_vel_dt;
    _P_pred(0, 1) = P(0, 1) + P(3, 1) * delta_vel_dt + _tmp94 * delta_vel_dt;
    _P_pred(1, 1) = P(1, 1) + P(4, 1) * delta_vel_dt + _tmp95 * delta_vel_dt;
    _P_pred(2, 1) = P(2, 1) + P(5, 1) * delta_vel_dt + _tmp96 * delta_vel_dt;
    _P_pred(3, 1) = -P(10, 1) * _tmp54 - P(11, 1) * _tmp55 + P(3, 1) + P(6, 1) * _tmp51 +
                    P(7, 1) * _tmp47 + P(8, 1) * _tmp48 - P(9, 1) * _tmp53 + _tmp100 * delta_vel_dt;
    _P_pred(4, 1) = -P(10, 1) * _tmp62 - P(11, 1) * _tmp61 + P(4, 1) + P(6, 1) * _tmp57 +
                    P(7, 1) * _tmp56 + P(8, 1) * _tmp58 - P(9, 1) * _tmp60 + _tmp101 * delta_vel_dt;
    _P_pred(5, 1) = -P(10, 1) * _tmp68 - P(11, 1) * _tmp69 + P(5, 1) + P(6, 1) * _tmp63 +
                    P(7, 1) * _tmp65 + P(8, 1) * _tmp64 - P(9, 1) * _tmp67 + _tmp102 * delta_vel_dt;
    _P_pred(6, 1) = -P(12, 1) * delta_angle_dt + P(6, 1) * _tmp78 + P(7, 1) * _tmp81 +
                    P(8, 1) * _tmp75 + _tmp103 * delta_vel_dt;
    _P_pred(7, 1) = -P(13, 1) * delta_angle_dt + P(6, 1) * _tmp83 + P(7, 1) * _tmp88 +
                    P(8, 1) * _tmp86 + _tmp104 * delta_vel_dt;
    _P_pred(8, 1) = -P(14, 1) * delta_angle_dt + P(6, 1) * _tmp91 + P(7, 1) * _tmp92 +
                    P(8, 1) * _tmp90 + _tmp105 * delta_vel_dt;
    _P_pred(9, 1) = P(9, 1) + _tmp97;
    _P_pred(10, 1) = P(10, 1) + _tmp98;
    _P_pred(11, 1) = P(11, 1) + _tmp99;
    _P_pred(12, 1) = P(12, 1) + P(12, 4) * delta_vel_dt;
    _P_pred(13, 1) = P(13, 1) + P(13, 4) * delta_vel_dt;
    _P_pred(14, 1) = P(14, 1) + P(14, 4) * delta_vel_dt;
    _P_pred(0, 2) = P(0, 2) + P(3, 2) * delta_vel_dt + _tmp106 * delta_vel_dt;
    _P_pred(1, 2) = P(1, 2) + P(4, 2) * delta_vel_dt + _tmp107 * delta_vel_dt;
    _P_pred(2, 2) = P(2, 2) + P(5, 2) * delta_vel_dt + _tmp108 * delta_vel_dt;
    _P_pred(3, 2) = -P(10, 2) * _tmp54 - P(11, 2) * _tmp55 + P(3, 2) + P(6, 2) * _tmp51 +
                    P(7, 2) * _tmp47 + P(8, 2) * _tmp48 - P(9, 2) * _tmp53 + _tmp112 * delta_vel_dt;
    _P_pred(4, 2) = -P(10, 2) * _tmp62 - P(11, 2) * _tmp61 + P(4, 2) + P(6, 2) * _tmp57 +
                    P(7, 2) * _tmp56 + P(8, 2) * _tmp58 - P(9, 2) * _tmp60 + _tmp113 * delta_vel_dt;
    _P_pred(5, 2) = -P(10, 2) * _tmp68 - P(11, 2) * _tmp69 + P(5, 2) + P(6, 2) * _tmp63 +
                    P(7, 2) * _tmp65 + P(8, 2) * _tmp64 - P(9, 2) * _tmp67 + _tmp114 * delta_vel_dt;
    _P_pred(6, 2) = -P(12, 2) * delta_angle_dt + P(6, 2) * _tmp78 + P(7, 2) * _tmp81 +
                    P(8, 2) * _tmp75 + _tmp115 * delta_vel_dt;
    _P_pred(7, 2) = -P(13, 2) * delta_angle_dt + P(6, 2) * _tmp83 + P(7, 2) * _tmp88 +
                    P(8, 2) * _tmp86 + _tmp116 * delta_vel_dt;
    _P_pred(8, 2) = -P(14, 2) * delta_angle_dt + P(6, 2) * _tmp91 + P(7, 2) * _tmp92 +
                    P(8, 2) * _tmp90 + _tmp117 * delta_vel_dt;
    _P_pred(9, 2) = P(9, 2) + _tmp109;
    _P_pred(10, 2) = P(10, 2) + _tmp110;
    _P_pred(11, 2) = P(11, 2) + _tmp111;
    _P_pred(12, 2) = P(12, 2) + P(12, 5) * delta_vel_dt;
    _P_pred(13, 2) = P(13, 2) + P(13, 5) * delta_vel_dt;
    _P_pred(14, 2) = P(14, 2) + P(14, 5) * delta_vel_dt;
    _P_pred(0, 3) = _tmp118 * _tmp51 + _tmp119 * _tmp48 - _tmp120 * _tmp55 - _tmp121 * _tmp54 -
                    _tmp122 * _tmp53 + _tmp123 * _tmp47 + _tmp43;
    _P_pred(1, 3) = _tmp124 * _tmp51 + _tmp125 * _tmp48 - _tmp126 * _tmp55 - _tmp127 * _tmp54 +
                    _tmp128 * _tmp47 - _tmp129 * _tmp53 + _tmp44;
    _P_pred(2, 3) = _tmp130 * _tmp51 + _tmp131 * _tmp48 + _tmp132 * _tmp47 - _tmp133 * _tmp54 -
                    _tmp134 * _tmp55 - _tmp135 * _tmp53 + _tmp45;
    _P_pred(3, 3) = _tmp136 - _tmp138 * _tmp53 + _tmp139 * _tmp51 + _tmp140 * _tmp48 +
                    _tmp141 * _tmp47 - _tmp143 * _tmp54 - _tmp145 * _tmp55 + _tmp52;
    _P_pred(4, 3) = -_tmp147 * _tmp55 - _tmp149 * _tmp54 - _tmp151 * _tmp53 + _tmp152 * _tmp47 +
                    _tmp153 * _tmp51 + _tmp154 * _tmp48 + _tmp59;
    _P_pred(5, 3) = -_tmp156 * _tmp53 + _tmp157 * _tmp51 - _tmp159 * _tmp55 - _tmp161 * _tmp54 +
                    _tmp162 * _tmp47 + _tmp163 * _tmp48 + _tmp66;
    _P_pred(6, 3) = -_tmp12 * _tmp170 + _tmp164 * _tmp47 + _tmp165 * _tmp48 - _tmp166 * _tmp54 -
                    _tmp167 * _tmp55 + _tmp168 * _tmp51 + _tmp82;
    _P_pred(7, 3) = _tmp171 * _tmp47 - _tmp172 * _tmp53 + _tmp173 * _tmp48 + _tmp174 * _tmp51 -
                    _tmp175 * _tmp55 - _tmp176 * _tmp54 + _tmp89;
    _P_pred(8, 3) = -_tmp177 * _tmp53 + _tmp178 * _tmp51 - _tmp179 * _tmp54 - _tmp180 * _tmp55 +
                    _tmp181 * _tmp47 + _tmp182 * _tmp48 + _tmp93;
    _P_pred(9, 3) = -P(9, 10) * _tmp54 - P(9, 11) * _tmp55 + P(9, 3) + P(9, 6) * _tmp51 +
                    P(9, 7) * _tmp47 + P(9, 8) * _tmp48 + _tmp137;
    _P_pred(10, 3) = -P(10, 11) * _tmp55 + P(10, 3) + P(10, 6) * _tmp51 + P(10, 7) * _tmp47 +
                     P(10, 8) * _tmp48 - P(10, 9) * _tmp53 + _tmp142;
    _P_pred(11, 3) = -P(11, 10) * _tmp54 + P(11, 3) + P(11, 6) * _tmp51 + P(11, 7) * _tmp47 +
                     P(11, 8) * _tmp48 - P(11, 9) * _tmp53 + _tmp144;
    _P_pred(12, 3) = -P(12, 10) * _tmp54 - P(12, 11) * _tmp55 + P(12, 3) + P(12, 6) * _tmp51 +
                     P(12, 7) * _tmp47 + P(12, 8) * _tmp48 - P(12, 9) * _tmp53;
    _P_pred(13, 3) = -P(13, 10) * _tmp54 - P(13, 11) * _tmp55 + P(13, 3) + P(13, 6) * _tmp51 +
                     P(13, 7) * _tmp47 + P(13, 8) * _tmp48 - P(13, 9) * _tmp53;
    _P_pred(14, 3) = -P(14, 10) * _tmp54 - P(14, 11) * _tmp55 + P(14, 3) + P(14, 6) * _tmp51 +
                     P(14, 7) * _tmp47 + P(14, 8) * _tmp48 - P(14, 9) * _tmp53;
    _P_pred(0, 4) = _tmp118 * _tmp57 + _tmp119 * _tmp58 - _tmp120 * _tmp61 - _tmp121 * _tmp62 -
                    _tmp122 * _tmp60 + _tmp123 * _tmp56 + _tmp94;
    _P_pred(1, 4) = _tmp124 * _tmp57 + _tmp125 * _tmp58 - _tmp126 * _tmp61 - _tmp127 * _tmp62 +
                    _tmp128 * _tmp56 - _tmp183 * _tmp21 + _tmp95;
    _P_pred(2, 4) = _tmp130 * _tmp57 + _tmp131 * _tmp58 + _tmp132 * _tmp56 - _tmp133 * _tmp62 -
                    _tmp134 * _tmp61 - _tmp184 * _tmp21 + _tmp96;
    _P_pred(3, 4) = _tmp100 + _tmp139 * _tmp57 + _tmp140 * _tmp58 + _tmp141 * _tmp56 -
                    _tmp143 * _tmp62 - _tmp145 * _tmp61 - _tmp185 * _tmp21;
    _P_pred(4, 4) = _tmp101 + _tmp136 - _tmp147 * _tmp61 - _tmp149 * _tmp62 - _tmp151 * _tmp60 +
                    _tmp152 * _tmp56 + _tmp153 * _tmp57 + _tmp154 * _tmp58;
    _P_pred(5, 4) = _tmp102 + _tmp157 * _tmp57 - _tmp159 * _tmp61 - _tmp161 * _tmp62 +
                    _tmp162 * _tmp56 + _tmp163 * _tmp58 - _tmp186 * _tmp21;
    _P_pred(6, 4) = _tmp103 + _tmp164 * _tmp56 + _tmp165 * _tmp58 - _tmp166 * _tmp62 -
                    _tmp167 * _tmp61 + _tmp168 * _tmp57 - _tmp170 * _tmp21;
    _P_pred(7, 4) = _tmp104 + _tmp171 * _tmp56 - _tmp172 * _tmp60 + _tmp173 * _tmp58 +
                    _tmp174 * _tmp57 - _tmp175 * _tmp61 - _tmp176 * _tmp62;
    _P_pred(8, 4) = _tmp105 - _tmp177 * _tmp60 + _tmp178 * _tmp57 - _tmp179 * _tmp62 -
                    _tmp180 * _tmp61 + _tmp181 * _tmp56 + _tmp182 * _tmp58;
    _P_pred(9, 4) = -P(9, 10) * _tmp62 - P(9, 11) * _tmp61 + P(9, 4) + P(9, 6) * _tmp57 +
                    P(9, 7) * _tmp56 + P(9, 8) * _tmp58 + _tmp150;
    _P_pred(10, 4) = -P(10, 11) * _tmp61 + P(10, 4) + P(10, 6) * _tmp57 + P(10, 7) * _tmp56 +
                     P(10, 8) * _tmp58 - P(10, 9) * _tmp60 + _tmp148;
    _P_pred(11, 4) = -P(11, 10) * _tmp62 + P(11, 4) + P(11, 6) * _tmp57 + P(11, 7) * _tmp56 +
                     P(11, 8) * _tmp58 - P(11, 9) * _tmp60 + _tmp146;
    _P_pred(12, 4) = -P(12, 10) * _tmp62 - P(12, 11) * _tmp61 + P(12, 4) + P(12, 6) * _tmp57 +
                     P(12, 7) * _tmp56 + P(12, 8) * _tmp58 - P(12, 9) * _tmp60;
    _P_pred(13, 4) = -P(13, 10) * _tmp62 - P(13, 11) * _tmp61 + P(13, 4) + P(13, 6) * _tmp57 +
                     P(13, 7) * _tmp56 + P(13, 8) * _tmp58 - P(13, 9) * _tmp60;
    _P_pred(14, 4) = -P(14, 10) * _tmp62 - P(14, 11) * _tmp61 + P(14, 4) + P(14, 6) * _tmp57 +
                     P(14, 7) * _tmp56 + P(14, 8) * _tmp58 - P(14, 9) * _tmp60;
    _P_pred(0, 5) = _tmp106 + _tmp118 * _tmp63 + _tmp119 * _tmp64 - _tmp120 * _tmp69 -
                    _tmp121 * _tmp68 - _tmp122 * _tmp67 + _tmp123 * _tmp65;
    _P_pred(1, 5) = _tmp107 + _tmp124 * _tmp63 + _tmp125 * _tmp64 - _tmp126 * _tmp69 -
                    _tmp127 * _tmp68 + _tmp128 * _tmp65 - _tmp183 * _tmp25;
    _P_pred(2, 5) = _tmp108 + _tmp130 * _tmp63 + _tmp131 * _tmp64 + _tmp132 * _tmp65 -
                    _tmp133 * _tmp68 - _tmp134 * _tmp69 - _tmp184 * _tmp25;
    _P_pred(3, 5) = _tmp112 + _tmp139 * _tmp63 + _tmp140 * _tmp64 + _tmp141 * _tmp65 -
                    _tmp143 * _tmp68 - _tmp145 * _tmp69 - _tmp185 * _tmp25;
    _P_pred(4, 5) = _tmp113 - _tmp147 * _tmp69 - _tmp149 * _tmp68 - _tmp151 * _tmp67 +
                    _tmp152 * _tmp65 + _tmp153 * _tmp63 + _tmp154 * _tmp64;
    _P_pred(5, 5) = _tmp114 + _tmp136 + _tmp157 * _tmp63 - _tmp159 * _tmp69 - _tmp161 * _tmp68 +
                    _tmp162 * _tmp65 + _tmp163 * _tmp64 - _tmp186 * _tmp25;
    _P_pred(6, 5) = _tmp115 + _tmp164 * _tmp65 + _tmp165 * _tmp64 - _tmp166 * _tmp68 -
                    _tmp167 * _tmp69 + _tmp168 * _tmp63 - _tmp170 * _tmp25;
    _P_pred(7, 5) = _tmp116 + _tmp171 * _tmp65 - _tmp172 * _tmp67 + _tmp173 * _tmp64 +
                    _tmp174 * _tmp63 - _tmp175 * _tmp69 - _tmp176 * _tmp68;
    _P_pred(8, 5) = _tmp117 - _tmp177 * _tmp67 + _tmp178 * _tmp63 - _tmp179 * _tmp68 -
                    _tmp180 * _tmp69 + _tmp181 * _tmp65 + _tmp182 * _tmp64;
    _P_pred(9, 5) = -P(9, 10) * _tmp68 - P(9, 11) * _tmp69 + P(9, 5) + P(9, 6) * _tmp63 +
                    P(9, 7) * _tmp65 + P(9, 8) * _tmp64 + _tmp155;
    _P_pred(10, 5) = -P(10, 11) * _tmp69 + P(10, 5) + P(10, 6) * _tmp63 + P(10, 7) * _tmp65 +
                     P(10, 8) * _tmp64 - P(10, 9) * _tmp67 + _tmp160;
    _P_pred(11, 5) = -P(11, 10) * _tmp68 + P(11, 5) + P(11, 6) * _tmp63 + P(11, 7) * _tmp65 +
                     P(11, 8) * _tmp64 - P(11, 9) * _tmp67 + _tmp158;
    _P_pred(12, 5) = -P(12, 10) * _tmp68 - P(12, 11) * _tmp69 + P(12, 5) + P(12, 6) * _tmp63 +
                     P(12, 7) * _tmp65 + P(12, 8) * _tmp64 - P(12, 9) * _tmp67;
    _P_pred(13, 5) = -P(13, 10) * _tmp68 - P(13, 11) * _tmp69 + P(13, 5) + P(13, 6) * _tmp63 +
                     P(13, 7) * _tmp65 + P(13, 8) * _tmp64 - P(13, 9) * _tmp67;
    _P_pred(14, 5) = -P(14, 10) * _tmp68 - P(14, 11) * _tmp69 + P(14, 5) + P(14, 6) * _tmp63 +
                     P(14, 7) * _tmp65 + P(14, 8) * _tmp64 - P(14, 9) * _tmp67;
    _P_pred(0, 6) =
        _tmp118 * _tmp78 + _tmp119 * _tmp75 + _tmp123 * _tmp81 - _tmp187 * delta_angle_dt;
    _P_pred(1, 6) =
        _tmp124 * _tmp78 + _tmp125 * _tmp75 + _tmp128 * _tmp81 - _tmp188 * delta_angle_dt;
    _P_pred(2, 6) =
        _tmp130 * _tmp78 + _tmp131 * _tmp75 + _tmp132 * _tmp81 - _tmp189 * delta_angle_dt;
    _P_pred(3, 6) =
        _tmp139 * _tmp78 + _tmp140 * _tmp75 + _tmp141 * _tmp81 - _tmp190 * delta_angle_dt;
    _P_pred(4, 6) =
        _tmp152 * _tmp81 + _tmp153 * _tmp78 + _tmp154 * _tmp75 - _tmp191 * delta_angle_dt;
    _P_pred(5, 6) =
        _tmp157 * _tmp78 + _tmp162 * _tmp81 + _tmp163 * _tmp75 - _tmp192 * delta_angle_dt;
    _P_pred(6, 6) =
        _tmp164 * _tmp81 + _tmp165 * _tmp75 + _tmp168 * _tmp78 - _tmp194 * delta_angle_dt + _tmp195;
    _P_pred(7, 6) =
        _tmp171 * _tmp81 + _tmp173 * _tmp75 + _tmp174 * _tmp78 - _tmp197 * delta_angle_dt;
    _P_pred(8, 6) =
        _tmp178 * _tmp78 + _tmp181 * _tmp81 + _tmp182 * _tmp75 - _tmp199 * delta_angle_dt;
    _P_pred(9, 6) =
        -P(9, 12) * delta_angle_dt + P(9, 6) * _tmp78 + P(9, 7) * _tmp81 + P(9, 8) * _tmp75;
    _P_pred(10, 6) =
        -P(10, 12) * delta_angle_dt + P(10, 6) * _tmp78 + P(10, 7) * _tmp81 + P(10, 8) * _tmp75;
    _P_pred(11, 6) =
        -P(11, 12) * delta_angle_dt + P(11, 6) * _tmp78 + P(11, 7) * _tmp81 + P(11, 8) * _tmp75;
    _P_pred(12, 6) = P(12, 6) * _tmp78 + P(12, 7) * _tmp81 + P(12, 8) * _tmp75 + _tmp193;
    _P_pred(13, 6) = P(13, 6) * _tmp78 + P(13, 7) * _tmp81 + P(13, 8) * _tmp75 + _tmp196;
    _P_pred(14, 6) = P(14, 6) * _tmp78 + P(14, 7) * _tmp81 + P(14, 8) * _tmp75 + _tmp198;
    _P_pred(0, 7) =
        _tmp118 * _tmp83 + _tmp119 * _tmp86 + _tmp123 * _tmp88 - _tmp200 * delta_angle_dt;
    _P_pred(1, 7) =
        _tmp124 * _tmp83 + _tmp125 * _tmp86 + _tmp128 * _tmp88 - _tmp201 * delta_angle_dt;
    _P_pred(2, 7) =
        _tmp130 * _tmp83 + _tmp131 * _tmp86 + _tmp132 * _tmp88 - _tmp202 * delta_angle_dt;
    _P_pred(3, 7) =
        _tmp139 * _tmp83 + _tmp140 * _tmp86 + _tmp141 * _tmp88 - _tmp203 * delta_angle_dt;
    _P_pred(4, 7) =
        _tmp152 * _tmp88 + _tmp153 * _tmp83 + _tmp154 * _tmp86 - _tmp204 * delta_angle_dt;
    _P_pred(5, 7) =
        _tmp157 * _tmp83 + _tmp162 * _tmp88 + _tmp163 * _tmp86 - _tmp205 * delta_angle_dt;
    _P_pred(6, 7) =
        _tmp164 * _tmp88 + _tmp165 * _tmp86 + _tmp168 * _tmp83 - _tmp207 * delta_angle_dt;
    _P_pred(7, 7) =
        _tmp171 * _tmp88 + _tmp173 * _tmp86 + _tmp174 * _tmp83 + _tmp195 - _tmp209 * delta_angle_dt;
    _P_pred(8, 7) =
        _tmp178 * _tmp83 + _tmp181 * _tmp88 + _tmp182 * _tmp86 - _tmp211 * delta_angle_dt;
    _P_pred(9, 7) =
        -P(9, 13) * delta_angle_dt + P(9, 6) * _tmp83 + P(9, 7) * _tmp88 + P(9, 8) * _tmp86;
    _P_pred(10, 7) =
        -P(10, 13) * delta_angle_dt + P(10, 6) * _tmp83 + P(10, 7) * _tmp88 + P(10, 8) * _tmp86;
    _P_pred(11, 7) =
        -P(11, 13) * delta_angle_dt + P(11, 6) * _tmp83 + P(11, 7) * _tmp88 + P(11, 8) * _tmp86;
    _P_pred(12, 7) = P(12, 6) * _tmp83 + P(12, 7) * _tmp88 + P(12, 8) * _tmp86 + _tmp206;
    _P_pred(13, 7) = P(13, 6) * _tmp83 + P(13, 7) * _tmp88 + P(13, 8) * _tmp86 + _tmp208;
    _P_pred(14, 7) = P(14, 6) * _tmp83 + P(14, 7) * _tmp88 + P(14, 8) * _tmp86 + _tmp210;
    _P_pred(0, 8) =
        _tmp118 * _tmp91 + _tmp119 * _tmp90 + _tmp123 * _tmp92 - _tmp212 * delta_angle_dt;
    _P_pred(1, 8) =
        _tmp124 * _tmp91 + _tmp125 * _tmp90 + _tmp128 * _tmp92 - _tmp213 * delta_angle_dt;
    _P_pred(2, 8) =
        _tmp130 * _tmp91 + _tmp131 * _tmp90 + _tmp132 * _tmp92 - _tmp214 * delta_angle_dt;
    _P_pred(3, 8) =
        _tmp139 * _tmp91 + _tmp140 * _tmp90 + _tmp141 * _tmp92 - _tmp215 * delta_angle_dt;
    _P_pred(4, 8) =
        _tmp152 * _tmp92 + _tmp153 * _tmp91 + _tmp154 * _tmp90 - _tmp216 * delta_angle_dt;
    _P_pred(5, 8) =
        _tmp157 * _tmp91 + _tmp162 * _tmp92 + _tmp163 * _tmp90 - _tmp217 * delta_angle_dt;
    _P_pred(6, 8) =
        _tmp164 * _tmp92 + _tmp165 * _tmp90 + _tmp168 * _tmp91 - _tmp219 * delta_angle_dt;
    _P_pred(7, 8) =
        _tmp171 * _tmp92 + _tmp173 * _tmp90 + _tmp174 * _tmp91 - _tmp221 * delta_angle_dt;
    _P_pred(8, 8) =
        _tmp178 * _tmp91 + _tmp181 * _tmp92 + _tmp182 * _tmp90 + _tmp195 - _tmp223 * delta_angle_dt;
    _P_pred(9, 8) =
        -P(9, 14) * delta_angle_dt + P(9, 6) * _tmp91 + P(9, 7) * _tmp92 + P(9, 8) * _tmp90;
    _P_pred(10, 8) =
        -P(10, 14) * delta_angle_dt + P(10, 6) * _tmp91 + P(10, 7) * _tmp92 + P(10, 8) * _tmp90;
    _P_pred(11, 8) =
        -P(11, 14) * delta_angle_dt + P(11, 6) * _tmp91 + P(11, 7) * _tmp92 + P(11, 8) * _tmp90;
    _P_pred(12, 8) = P(12, 6) * _tmp91 + P(12, 7) * _tmp92 + P(12, 8) * _tmp90 + _tmp218;
    _P_pred(13, 8) = P(13, 6) * _tmp91 + P(13, 7) * _tmp92 + P(13, 8) * _tmp90 + _tmp220;
    _P_pred(14, 8) = P(14, 6) * _tmp91 + P(14, 7) * _tmp92 + P(14, 8) * _tmp90 + _tmp222;
    _P_pred(0, 9) = _tmp122;
    _P_pred(1, 9) = _tmp129;
    _P_pred(2, 9) = _tmp135;
    _P_pred(3, 9) = _tmp138;
    _P_pred(4, 9) = _tmp151;
    _P_pred(5, 9) = _tmp156;
    _P_pred(6, 9) = _tmp169;
    _P_pred(7, 9) = _tmp172;
    _P_pred(8, 9) = _tmp177;
    _P_pred(9, 9) = P(9, 9) + _tmp224;
    _P_pred(10, 9) = P(10, 9);
    _P_pred(11, 9) = P(11, 9);
    _P_pred(12, 9) = P(12, 9);
    _P_pred(13, 9) = P(13, 9);
    _P_pred(14, 9) = P(14, 9);
    _P_pred(0, 10) = _tmp121;
    _P_pred(1, 10) = _tmp127;
    _P_pred(2, 10) = _tmp133;
    _P_pred(3, 10) = _tmp143;
    _P_pred(4, 10) = _tmp149;
    _P_pred(5, 10) = _tmp161;
    _P_pred(6, 10) = _tmp166;
    _P_pred(7, 10) = _tmp176;
    _P_pred(8, 10) = _tmp179;
    _P_pred(9, 10) = P(9, 10);
    _P_pred(10, 10) = P(10, 10) + _tmp224;
    _P_pred(11, 10) = P(11, 10);
    _P_pred(12, 10) = P(12, 10);
    _P_pred(13, 10) = P(13, 10);
    _P_pred(14, 10) = P(14, 10);
    _P_pred(0, 11) = _tmp120;
    _P_pred(1, 11) = _tmp126;
    _P_pred(2, 11) = _tmp134;
    _P_pred(3, 11) = _tmp145;
    _P_pred(4, 11) = _tmp147;
    _P_pred(5, 11) = _tmp159;
    _P_pred(6, 11) = _tmp167;
    _P_pred(7, 11) = _tmp175;
    _P_pred(8, 11) = _tmp180;
    _P_pred(9, 11) = P(9, 11);
    _P_pred(10, 11) = P(10, 11);
    _P_pred(11, 11) = P(11, 11) + _tmp224;
    _P_pred(12, 11) = P(12, 11);
    _P_pred(13, 11) = P(13, 11);
    _P_pred(14, 11) = P(14, 11);
    _P_pred(0, 12) = _tmp187;
    _P_pred(1, 12) = _tmp188;
    _P_pred(2, 12) = _tmp189;
    _P_pred(3, 12) = _tmp190;
    _P_pred(4, 12) = _tmp191;
    _P_pred(5, 12) = _tmp192;
    _P_pred(6, 12) = _tmp194;
    _P_pred(7, 12) = _tmp197;
    _P_pred(8, 12) = _tmp199;
    _P_pred(9, 12) = P(9, 12);
    _P_pred(10, 12) = P(10, 12);
    _P_pred(11, 12) = P(11, 12);
    _P_pred(12, 12) = P(12, 12) + _tmp225;
    _P_pred(13, 12) = P(13, 12);
    _P_pred(14, 12) = P(14, 12);
    _P_pred(0, 13) = _tmp200;
    _P_pred(1, 13) = _tmp201;
    _P_pred(2, 13) = _tmp202;
    _P_pred(3, 13) = _tmp203;
    _P_pred(4, 13) = _tmp204;
    _P_pred(5, 13) = _tmp205;
    _P_pred(6, 13) = _tmp207;
    _P_pred(7, 13) = _tmp209;
    _P_pred(8, 13) = _tmp211;
    _P_pred(9, 13) = P(9, 13);
    _P_pred(10, 13) = P(10, 13);
    _P_pred(11, 13) = P(11, 13);
    _P_pred(12, 13) = P(12, 13);
    _P_pred(13, 13) = P(13, 13) + _tmp225;
    _P_pred(14, 13) = P(14, 13);
    _P_pred(0, 14) = _tmp212;
    _P_pred(1, 14) = _tmp213;
    _P_pred(2, 14) = _tmp214;
    _P_pred(3, 14) = _tmp215;
    _P_pred(4, 14) = _tmp216;
    _P_pred(5, 14) = _tmp217;
    _P_pred(6, 14) = _tmp219;
    _P_pred(7, 14) = _tmp221;
    _P_pred(8, 14) = _tmp223;
    _P_pred(9, 14) = P(9, 14);
    _P_pred(10, 14) = P(10, 14);
    _P_pred(11, 14) = P(11, 14);
    _P_pred(12, 14) = P(12, 14);
    _P_pred(13, 14) = P(13, 14);
    _P_pred(14, 14) = P(14, 14) + _tmp225;
  }
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace gnc
